// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"dealscanner/internal/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newActionRegistry(db *gorm.DB, opts ...gen.DOOption) actionRegistry {
	_actionRegistry := actionRegistry{}

	_actionRegistry.actionRegistryDo.UseDB(db, opts...)
	_actionRegistry.actionRegistryDo.UseModel(&models.ActionRegistry{})

	tableName := _actionRegistry.actionRegistryDo.TableName()
	_actionRegistry.ALL = field.NewAsterisk(tableName)
	_actionRegistry.ID = field.NewString(tableName, "id")
	_actionRegistry.Type = field.NewString(tableName, "type")
	_actionRegistry.QueryType = field.NewString(tableName, "queryType")
	_actionRegistry.QueryId = field.NewString(tableName, "queryId")
	_actionRegistry.UserId = field.NewString(tableName, "userId")
	_actionRegistry.Timestamp = field.NewInt64(tableName, "timestamp")
	_actionRegistry.RelatedKey = field.NewString(tableName, "relatedKey")
	_actionRegistry.CreatedAt = field.NewTime(tableName, "createdAt")

	_actionRegistry.fillFieldMap()

	return _actionRegistry
}

type actionRegistry struct {
	actionRegistryDo actionRegistryDo

	ALL        field.Asterisk
	ID         field.String
	Type       field.String
	QueryType  field.String
	QueryId    field.String
	UserId     field.String
	Timestamp  field.Int64
	RelatedKey field.String
	CreatedAt  field.Time

	fieldMap map[string]field.Expr
}

func (a actionRegistry) Table(newTableName string) *actionRegistry {
	a.actionRegistryDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a actionRegistry) As(alias string) *actionRegistry {
	a.actionRegistryDo.DO = *(a.actionRegistryDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *actionRegistry) updateTableName(table string) *actionRegistry {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewString(table, "id")
	a.Type = field.NewString(table, "type")
	a.QueryType = field.NewString(table, "queryType")
	a.QueryId = field.NewString(table, "queryId")
	a.UserId = field.NewString(table, "userId")
	a.Timestamp = field.NewInt64(table, "timestamp")
	a.RelatedKey = field.NewString(table, "relatedKey")
	a.CreatedAt = field.NewTime(table, "createdAt")

	a.fillFieldMap()

	return a
}

func (a *actionRegistry) WithContext(ctx context.Context) IActionRegistryDo {
	return a.actionRegistryDo.WithContext(ctx)
}

func (a actionRegistry) TableName() string { return a.actionRegistryDo.TableName() }

func (a actionRegistry) Alias() string { return a.actionRegistryDo.Alias() }

func (a actionRegistry) Columns(cols ...field.Expr) gen.Columns {
	return a.actionRegistryDo.Columns(cols...)
}

func (a *actionRegistry) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *actionRegistry) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 8)
	a.fieldMap["id"] = a.ID
	a.fieldMap["type"] = a.Type
	a.fieldMap["queryType"] = a.QueryType
	a.fieldMap["queryId"] = a.QueryId
	a.fieldMap["userId"] = a.UserId
	a.fieldMap["timestamp"] = a.Timestamp
	a.fieldMap["relatedKey"] = a.RelatedKey
	a.fieldMap["createdAt"] = a.CreatedAt
}

func (a actionRegistry) clone(db *gorm.DB) actionRegistry {
	a.actionRegistryDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a actionRegistry) replaceDB(db *gorm.DB) actionRegistry {
	a.actionRegistryDo.ReplaceDB(db)
	return a
}

type actionRegistryDo struct{ gen.DO }

type IActionRegistryDo interface {
	gen.SubQuery
	Debug() IActionRegistryDo
	WithContext(ctx context.Context) IActionRegistryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IActionRegistryDo
	WriteDB() IActionRegistryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IActionRegistryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IActionRegistryDo
	Not(conds ...gen.Condition) IActionRegistryDo
	Or(conds ...gen.Condition) IActionRegistryDo
	Select(conds ...field.Expr) IActionRegistryDo
	Where(conds ...gen.Condition) IActionRegistryDo
	Order(conds ...field.Expr) IActionRegistryDo
	Distinct(cols ...field.Expr) IActionRegistryDo
	Omit(cols ...field.Expr) IActionRegistryDo
	Join(table schema.Tabler, on ...field.Expr) IActionRegistryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IActionRegistryDo
	RightJoin(table schema.Tabler, on ...field.Expr) IActionRegistryDo
	Group(cols ...field.Expr) IActionRegistryDo
	Having(conds ...gen.Condition) IActionRegistryDo
	Limit(limit int) IActionRegistryDo
	Offset(offset int) IActionRegistryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IActionRegistryDo
	Unscoped() IActionRegistryDo
	Create(values ...*models.ActionRegistry) error
	CreateInBatches(values []*models.ActionRegistry, batchSize int) error
	Save(values ...*models.ActionRegistry) error
	First() (*models.ActionRegistry, error)
	Take() (*models.ActionRegistry, error)
	Last() (*models.ActionRegistry, error)
	Find() ([]*models.ActionRegistry, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ActionRegistry, err error)
	FindInBatches(result *[]*models.ActionRegistry, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.ActionRegistry) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IActionRegistryDo
	Assign(attrs ...field.AssignExpr) IActionRegistryDo
	Joins(fields ...field.RelationField) IActionRegistryDo
	Preload(fields ...field.RelationField) IActionRegistryDo
	FirstOrInit() (*models.ActionRegistry, error)
	FirstOrCreate() (*models.ActionRegistry, error)
	FindByPage(offset int, limit int) (result []*models.ActionRegistry, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IActionRegistryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a actionRegistryDo) Debug() IActionRegistryDo {
	return a.withDO(a.DO.Debug())
}

func (a actionRegistryDo) WithContext(ctx context.Context) IActionRegistryDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a actionRegistryDo) ReadDB() IActionRegistryDo {
	return a.Clauses(dbresolver.Read)
}

func (a actionRegistryDo) WriteDB() IActionRegistryDo {
	return a.Clauses(dbresolver.Write)
}

func (a actionRegistryDo) Session(config *gorm.Session) IActionRegistryDo {
	return a.withDO(a.DO.Session(config))
}

func (a actionRegistryDo) Clauses(conds ...clause.Expression) IActionRegistryDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a actionRegistryDo) Returning(value interface{}, columns ...string) IActionRegistryDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a actionRegistryDo) Not(conds ...gen.Condition) IActionRegistryDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a actionRegistryDo) Or(conds ...gen.Condition) IActionRegistryDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a actionRegistryDo) Select(conds ...field.Expr) IActionRegistryDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a actionRegistryDo) Where(conds ...gen.Condition) IActionRegistryDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a actionRegistryDo) Order(conds ...field.Expr) IActionRegistryDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a actionRegistryDo) Distinct(cols ...field.Expr) IActionRegistryDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a actionRegistryDo) Omit(cols ...field.Expr) IActionRegistryDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a actionRegistryDo) Join(table schema.Tabler, on ...field.Expr) IActionRegistryDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a actionRegistryDo) LeftJoin(table schema.Tabler, on ...field.Expr) IActionRegistryDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a actionRegistryDo) RightJoin(table schema.Tabler, on ...field.Expr) IActionRegistryDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a actionRegistryDo) Group(cols ...field.Expr) IActionRegistryDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a actionRegistryDo) Having(conds ...gen.Condition) IActionRegistryDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a actionRegistryDo) Limit(limit int) IActionRegistryDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a actionRegistryDo) Offset(offset int) IActionRegistryDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a actionRegistryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IActionRegistryDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a actionRegistryDo) Unscoped() IActionRegistryDo {
	return a.withDO(a.DO.Unscoped())
}

func (a actionRegistryDo) Create(values ...*models.ActionRegistry) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a actionRegistryDo) CreateInBatches(values []*models.ActionRegistry, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a actionRegistryDo) Save(values ...*models.ActionRegistry) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a actionRegistryDo) First() (*models.ActionRegistry, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.ActionRegistry), nil
	}
}

func (a actionRegistryDo) Take() (*models.ActionRegistry, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.ActionRegistry), nil
	}
}

func (a actionRegistryDo) Last() (*models.ActionRegistry, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.ActionRegistry), nil
	}
}

func (a actionRegistryDo) Find() ([]*models.ActionRegistry, error) {
	result, err := a.DO.Find()
	return result.([]*models.ActionRegistry), err
}

func (a actionRegistryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ActionRegistry, err error) {
	buf := make([]*models.ActionRegistry, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a actionRegistryDo) FindInBatches(result *[]*models.ActionRegistry, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a actionRegistryDo) Attrs(attrs ...field.AssignExpr) IActionRegistryDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a actionRegistryDo) Assign(attrs ...field.AssignExpr) IActionRegistryDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a actionRegistryDo) Joins(fields ...field.RelationField) IActionRegistryDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a actionRegistryDo) Preload(fields ...field.RelationField) IActionRegistryDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a actionRegistryDo) FirstOrInit() (*models.ActionRegistry, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.ActionRegistry), nil
	}
}

func (a actionRegistryDo) FirstOrCreate() (*models.ActionRegistry, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.ActionRegistry), nil
	}
}

func (a actionRegistryDo) FindByPage(offset int, limit int) (result []*models.ActionRegistry, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a actionRegistryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a actionRegistryDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a actionRegistryDo) Delete(models ...*models.ActionRegistry) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *actionRegistryDo) withDO(do gen.Dao) *actionRegistryDo {
	a.DO = *do.(*gen.DO)
	return a
}
