// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"dealscanner/internal/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newCashConverters(db *gorm.DB, opts ...gen.DOOption) cashConverters {
	_cashConverters := cashConverters{}

	_cashConverters.cashConvertersDo.UseDB(db, opts...)
	_cashConverters.cashConvertersDo.UseModel(&models.CashConverters{})

	tableName := _cashConverters.cashConvertersDo.TableName()
	_cashConverters.ALL = field.NewAsterisk(tableName)
	_cashConverters.Url = field.NewString(tableName, "url")
	_cashConverters.ScanMode = field.NewString(tableName, "scanMode")

	_cashConverters.fillFieldMap()

	return _cashConverters
}

type cashConverters struct {
	cashConvertersDo cashConvertersDo

	ALL      field.Asterisk
	Url      field.String
	ScanMode field.String

	fieldMap map[string]field.Expr
}

func (c cashConverters) Table(newTableName string) *cashConverters {
	c.cashConvertersDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cashConverters) As(alias string) *cashConverters {
	c.cashConvertersDo.DO = *(c.cashConvertersDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cashConverters) updateTableName(table string) *cashConverters {
	c.ALL = field.NewAsterisk(table)
	c.Url = field.NewString(table, "url")
	c.ScanMode = field.NewString(table, "scanMode")

	c.fillFieldMap()

	return c
}

func (c *cashConverters) WithContext(ctx context.Context) ICashConvertersDo {
	return c.cashConvertersDo.WithContext(ctx)
}

func (c cashConverters) TableName() string { return c.cashConvertersDo.TableName() }

func (c cashConverters) Alias() string { return c.cashConvertersDo.Alias() }

func (c cashConverters) Columns(cols ...field.Expr) gen.Columns {
	return c.cashConvertersDo.Columns(cols...)
}

func (c *cashConverters) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cashConverters) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 2)
	c.fieldMap["url"] = c.Url
	c.fieldMap["scanMode"] = c.ScanMode
}

func (c cashConverters) clone(db *gorm.DB) cashConverters {
	c.cashConvertersDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cashConverters) replaceDB(db *gorm.DB) cashConverters {
	c.cashConvertersDo.ReplaceDB(db)
	return c
}

type cashConvertersDo struct{ gen.DO }

type ICashConvertersDo interface {
	gen.SubQuery
	Debug() ICashConvertersDo
	WithContext(ctx context.Context) ICashConvertersDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICashConvertersDo
	WriteDB() ICashConvertersDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICashConvertersDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICashConvertersDo
	Not(conds ...gen.Condition) ICashConvertersDo
	Or(conds ...gen.Condition) ICashConvertersDo
	Select(conds ...field.Expr) ICashConvertersDo
	Where(conds ...gen.Condition) ICashConvertersDo
	Order(conds ...field.Expr) ICashConvertersDo
	Distinct(cols ...field.Expr) ICashConvertersDo
	Omit(cols ...field.Expr) ICashConvertersDo
	Join(table schema.Tabler, on ...field.Expr) ICashConvertersDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICashConvertersDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICashConvertersDo
	Group(cols ...field.Expr) ICashConvertersDo
	Having(conds ...gen.Condition) ICashConvertersDo
	Limit(limit int) ICashConvertersDo
	Offset(offset int) ICashConvertersDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICashConvertersDo
	Unscoped() ICashConvertersDo
	Create(values ...*models.CashConverters) error
	CreateInBatches(values []*models.CashConverters, batchSize int) error
	Save(values ...*models.CashConverters) error
	First() (*models.CashConverters, error)
	Take() (*models.CashConverters, error)
	Last() (*models.CashConverters, error)
	Find() ([]*models.CashConverters, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.CashConverters, err error)
	FindInBatches(result *[]*models.CashConverters, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.CashConverters) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICashConvertersDo
	Assign(attrs ...field.AssignExpr) ICashConvertersDo
	Joins(fields ...field.RelationField) ICashConvertersDo
	Preload(fields ...field.RelationField) ICashConvertersDo
	FirstOrInit() (*models.CashConverters, error)
	FirstOrCreate() (*models.CashConverters, error)
	FindByPage(offset int, limit int) (result []*models.CashConverters, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICashConvertersDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c cashConvertersDo) Debug() ICashConvertersDo {
	return c.withDO(c.DO.Debug())
}

func (c cashConvertersDo) WithContext(ctx context.Context) ICashConvertersDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cashConvertersDo) ReadDB() ICashConvertersDo {
	return c.Clauses(dbresolver.Read)
}

func (c cashConvertersDo) WriteDB() ICashConvertersDo {
	return c.Clauses(dbresolver.Write)
}

func (c cashConvertersDo) Session(config *gorm.Session) ICashConvertersDo {
	return c.withDO(c.DO.Session(config))
}

func (c cashConvertersDo) Clauses(conds ...clause.Expression) ICashConvertersDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cashConvertersDo) Returning(value interface{}, columns ...string) ICashConvertersDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cashConvertersDo) Not(conds ...gen.Condition) ICashConvertersDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cashConvertersDo) Or(conds ...gen.Condition) ICashConvertersDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cashConvertersDo) Select(conds ...field.Expr) ICashConvertersDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cashConvertersDo) Where(conds ...gen.Condition) ICashConvertersDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cashConvertersDo) Order(conds ...field.Expr) ICashConvertersDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cashConvertersDo) Distinct(cols ...field.Expr) ICashConvertersDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cashConvertersDo) Omit(cols ...field.Expr) ICashConvertersDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cashConvertersDo) Join(table schema.Tabler, on ...field.Expr) ICashConvertersDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cashConvertersDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICashConvertersDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cashConvertersDo) RightJoin(table schema.Tabler, on ...field.Expr) ICashConvertersDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cashConvertersDo) Group(cols ...field.Expr) ICashConvertersDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cashConvertersDo) Having(conds ...gen.Condition) ICashConvertersDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cashConvertersDo) Limit(limit int) ICashConvertersDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cashConvertersDo) Offset(offset int) ICashConvertersDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cashConvertersDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICashConvertersDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cashConvertersDo) Unscoped() ICashConvertersDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cashConvertersDo) Create(values ...*models.CashConverters) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cashConvertersDo) CreateInBatches(values []*models.CashConverters, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cashConvertersDo) Save(values ...*models.CashConverters) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cashConvertersDo) First() (*models.CashConverters, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.CashConverters), nil
	}
}

func (c cashConvertersDo) Take() (*models.CashConverters, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.CashConverters), nil
	}
}

func (c cashConvertersDo) Last() (*models.CashConverters, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.CashConverters), nil
	}
}

func (c cashConvertersDo) Find() ([]*models.CashConverters, error) {
	result, err := c.DO.Find()
	return result.([]*models.CashConverters), err
}

func (c cashConvertersDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.CashConverters, err error) {
	buf := make([]*models.CashConverters, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cashConvertersDo) FindInBatches(result *[]*models.CashConverters, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cashConvertersDo) Attrs(attrs ...field.AssignExpr) ICashConvertersDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cashConvertersDo) Assign(attrs ...field.AssignExpr) ICashConvertersDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cashConvertersDo) Joins(fields ...field.RelationField) ICashConvertersDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cashConvertersDo) Preload(fields ...field.RelationField) ICashConvertersDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cashConvertersDo) FirstOrInit() (*models.CashConverters, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.CashConverters), nil
	}
}

func (c cashConvertersDo) FirstOrCreate() (*models.CashConverters, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.CashConverters), nil
	}
}

func (c cashConvertersDo) FindByPage(offset int, limit int) (result []*models.CashConverters, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cashConvertersDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cashConvertersDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cashConvertersDo) Delete(models ...*models.CashConverters) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cashConvertersDo) withDO(do gen.Dao) *cashConvertersDo {
	c.DO = *do.(*gen.DO)
	return c
}
