// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"dealscanner/internal/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newCashConvertersFilter(db *gorm.DB, opts ...gen.DOOption) cashConvertersFilter {
	_cashConvertersFilter := cashConvertersFilter{}

	_cashConvertersFilter.cashConvertersFilterDo.UseDB(db, opts...)
	_cashConvertersFilter.cashConvertersFilterDo.UseModel(&models.CashConvertersFilter{})

	tableName := _cashConvertersFilter.cashConvertersFilterDo.TableName()
	_cashConvertersFilter.ALL = field.NewAsterisk(tableName)
	_cashConvertersFilter.ID = field.NewString(tableName, "id")
	_cashConvertersFilter.CashConvertersUrl = field.NewString(tableName, "cashConvertersUrl")
	_cashConvertersFilter.QueryId = field.NewString(tableName, "queryId")
	_cashConvertersFilter.RequiredPhrases = field.NewString(tableName, "requiredPhrases")
	_cashConvertersFilter.RequiredMatchMode = field.NewString(tableName, "requiredMatchMode")
	_cashConvertersFilter.ExcludePhrases = field.NewString(tableName, "excludePhrases")
	_cashConvertersFilter.ExcludeMatchMode = field.NewString(tableName, "excludeMatchMode")
	_cashConvertersFilter.MinPrice = field.NewFloat64(tableName, "minPrice")
	_cashConvertersFilter.MaxPrice = field.NewFloat64(tableName, "maxPrice")
	_cashConvertersFilter.CreatedAt = field.NewTime(tableName, "createdAt")
	_cashConvertersFilter.CashConverters = cashConvertersFilterBelongsToCashConverters{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("CashConverters", "models.CashConverters"),
	}

	_cashConvertersFilter.Query = cashConvertersFilterBelongsToQuery{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Query", "models.SearchQuery"),
	}

	_cashConvertersFilter.fillFieldMap()

	return _cashConvertersFilter
}

type cashConvertersFilter struct {
	cashConvertersFilterDo cashConvertersFilterDo

	ALL               field.Asterisk
	ID                field.String
	CashConvertersUrl field.String
	QueryId           field.String
	RequiredPhrases   field.String
	RequiredMatchMode field.String
	ExcludePhrases    field.String
	ExcludeMatchMode  field.String
	MinPrice          field.Float64
	MaxPrice          field.Float64
	CreatedAt         field.Time
	CashConverters    cashConvertersFilterBelongsToCashConverters

	Query cashConvertersFilterBelongsToQuery

	fieldMap map[string]field.Expr
}

func (c cashConvertersFilter) Table(newTableName string) *cashConvertersFilter {
	c.cashConvertersFilterDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cashConvertersFilter) As(alias string) *cashConvertersFilter {
	c.cashConvertersFilterDo.DO = *(c.cashConvertersFilterDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cashConvertersFilter) updateTableName(table string) *cashConvertersFilter {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewString(table, "id")
	c.CashConvertersUrl = field.NewString(table, "cashConvertersUrl")
	c.QueryId = field.NewString(table, "queryId")
	c.RequiredPhrases = field.NewString(table, "requiredPhrases")
	c.RequiredMatchMode = field.NewString(table, "requiredMatchMode")
	c.ExcludePhrases = field.NewString(table, "excludePhrases")
	c.ExcludeMatchMode = field.NewString(table, "excludeMatchMode")
	c.MinPrice = field.NewFloat64(table, "minPrice")
	c.MaxPrice = field.NewFloat64(table, "maxPrice")
	c.CreatedAt = field.NewTime(table, "createdAt")

	c.fillFieldMap()

	return c
}

func (c *cashConvertersFilter) WithContext(ctx context.Context) ICashConvertersFilterDo {
	return c.cashConvertersFilterDo.WithContext(ctx)
}

func (c cashConvertersFilter) TableName() string { return c.cashConvertersFilterDo.TableName() }

func (c cashConvertersFilter) Alias() string { return c.cashConvertersFilterDo.Alias() }

func (c cashConvertersFilter) Columns(cols ...field.Expr) gen.Columns {
	return c.cashConvertersFilterDo.Columns(cols...)
}

func (c *cashConvertersFilter) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cashConvertersFilter) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 12)
	c.fieldMap["id"] = c.ID
	c.fieldMap["cashConvertersUrl"] = c.CashConvertersUrl
	c.fieldMap["queryId"] = c.QueryId
	c.fieldMap["requiredPhrases"] = c.RequiredPhrases
	c.fieldMap["requiredMatchMode"] = c.RequiredMatchMode
	c.fieldMap["excludePhrases"] = c.ExcludePhrases
	c.fieldMap["excludeMatchMode"] = c.ExcludeMatchMode
	c.fieldMap["minPrice"] = c.MinPrice
	c.fieldMap["maxPrice"] = c.MaxPrice
	c.fieldMap["createdAt"] = c.CreatedAt

}

func (c cashConvertersFilter) clone(db *gorm.DB) cashConvertersFilter {
	c.cashConvertersFilterDo.ReplaceConnPool(db.Statement.ConnPool)
	c.CashConverters.db = db.Session(&gorm.Session{Initialized: true})
	c.CashConverters.db.Statement.ConnPool = db.Statement.ConnPool
	c.Query.db = db.Session(&gorm.Session{Initialized: true})
	c.Query.db.Statement.ConnPool = db.Statement.ConnPool
	return c
}

func (c cashConvertersFilter) replaceDB(db *gorm.DB) cashConvertersFilter {
	c.cashConvertersFilterDo.ReplaceDB(db)
	c.CashConverters.db = db.Session(&gorm.Session{})
	c.Query.db = db.Session(&gorm.Session{})
	return c
}

type cashConvertersFilterBelongsToCashConverters struct {
	db *gorm.DB

	field.RelationField
}

func (a cashConvertersFilterBelongsToCashConverters) Where(conds ...field.Expr) *cashConvertersFilterBelongsToCashConverters {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a cashConvertersFilterBelongsToCashConverters) WithContext(ctx context.Context) *cashConvertersFilterBelongsToCashConverters {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a cashConvertersFilterBelongsToCashConverters) Session(session *gorm.Session) *cashConvertersFilterBelongsToCashConverters {
	a.db = a.db.Session(session)
	return &a
}

func (a cashConvertersFilterBelongsToCashConverters) Model(m *models.CashConvertersFilter) *cashConvertersFilterBelongsToCashConvertersTx {
	return &cashConvertersFilterBelongsToCashConvertersTx{a.db.Model(m).Association(a.Name())}
}

func (a cashConvertersFilterBelongsToCashConverters) Unscoped() *cashConvertersFilterBelongsToCashConverters {
	a.db = a.db.Unscoped()
	return &a
}

type cashConvertersFilterBelongsToCashConvertersTx struct{ tx *gorm.Association }

func (a cashConvertersFilterBelongsToCashConvertersTx) Find() (result *models.CashConverters, err error) {
	return result, a.tx.Find(&result)
}

func (a cashConvertersFilterBelongsToCashConvertersTx) Append(values ...*models.CashConverters) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a cashConvertersFilterBelongsToCashConvertersTx) Replace(values ...*models.CashConverters) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a cashConvertersFilterBelongsToCashConvertersTx) Delete(values ...*models.CashConverters) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a cashConvertersFilterBelongsToCashConvertersTx) Clear() error {
	return a.tx.Clear()
}

func (a cashConvertersFilterBelongsToCashConvertersTx) Count() int64 {
	return a.tx.Count()
}

func (a cashConvertersFilterBelongsToCashConvertersTx) Unscoped() *cashConvertersFilterBelongsToCashConvertersTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type cashConvertersFilterBelongsToQuery struct {
	db *gorm.DB

	field.RelationField
}

func (a cashConvertersFilterBelongsToQuery) Where(conds ...field.Expr) *cashConvertersFilterBelongsToQuery {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a cashConvertersFilterBelongsToQuery) WithContext(ctx context.Context) *cashConvertersFilterBelongsToQuery {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a cashConvertersFilterBelongsToQuery) Session(session *gorm.Session) *cashConvertersFilterBelongsToQuery {
	a.db = a.db.Session(session)
	return &a
}

func (a cashConvertersFilterBelongsToQuery) Model(m *models.CashConvertersFilter) *cashConvertersFilterBelongsToQueryTx {
	return &cashConvertersFilterBelongsToQueryTx{a.db.Model(m).Association(a.Name())}
}

func (a cashConvertersFilterBelongsToQuery) Unscoped() *cashConvertersFilterBelongsToQuery {
	a.db = a.db.Unscoped()
	return &a
}

type cashConvertersFilterBelongsToQueryTx struct{ tx *gorm.Association }

func (a cashConvertersFilterBelongsToQueryTx) Find() (result *models.SearchQuery, err error) {
	return result, a.tx.Find(&result)
}

func (a cashConvertersFilterBelongsToQueryTx) Append(values ...*models.SearchQuery) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a cashConvertersFilterBelongsToQueryTx) Replace(values ...*models.SearchQuery) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a cashConvertersFilterBelongsToQueryTx) Delete(values ...*models.SearchQuery) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a cashConvertersFilterBelongsToQueryTx) Clear() error {
	return a.tx.Clear()
}

func (a cashConvertersFilterBelongsToQueryTx) Count() int64 {
	return a.tx.Count()
}

func (a cashConvertersFilterBelongsToQueryTx) Unscoped() *cashConvertersFilterBelongsToQueryTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type cashConvertersFilterDo struct{ gen.DO }

type ICashConvertersFilterDo interface {
	gen.SubQuery
	Debug() ICashConvertersFilterDo
	WithContext(ctx context.Context) ICashConvertersFilterDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICashConvertersFilterDo
	WriteDB() ICashConvertersFilterDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICashConvertersFilterDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICashConvertersFilterDo
	Not(conds ...gen.Condition) ICashConvertersFilterDo
	Or(conds ...gen.Condition) ICashConvertersFilterDo
	Select(conds ...field.Expr) ICashConvertersFilterDo
	Where(conds ...gen.Condition) ICashConvertersFilterDo
	Order(conds ...field.Expr) ICashConvertersFilterDo
	Distinct(cols ...field.Expr) ICashConvertersFilterDo
	Omit(cols ...field.Expr) ICashConvertersFilterDo
	Join(table schema.Tabler, on ...field.Expr) ICashConvertersFilterDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICashConvertersFilterDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICashConvertersFilterDo
	Group(cols ...field.Expr) ICashConvertersFilterDo
	Having(conds ...gen.Condition) ICashConvertersFilterDo
	Limit(limit int) ICashConvertersFilterDo
	Offset(offset int) ICashConvertersFilterDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICashConvertersFilterDo
	Unscoped() ICashConvertersFilterDo
	Create(values ...*models.CashConvertersFilter) error
	CreateInBatches(values []*models.CashConvertersFilter, batchSize int) error
	Save(values ...*models.CashConvertersFilter) error
	First() (*models.CashConvertersFilter, error)
	Take() (*models.CashConvertersFilter, error)
	Last() (*models.CashConvertersFilter, error)
	Find() ([]*models.CashConvertersFilter, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.CashConvertersFilter, err error)
	FindInBatches(result *[]*models.CashConvertersFilter, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.CashConvertersFilter) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICashConvertersFilterDo
	Assign(attrs ...field.AssignExpr) ICashConvertersFilterDo
	Joins(fields ...field.RelationField) ICashConvertersFilterDo
	Preload(fields ...field.RelationField) ICashConvertersFilterDo
	FirstOrInit() (*models.CashConvertersFilter, error)
	FirstOrCreate() (*models.CashConvertersFilter, error)
	FindByPage(offset int, limit int) (result []*models.CashConvertersFilter, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICashConvertersFilterDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c cashConvertersFilterDo) Debug() ICashConvertersFilterDo {
	return c.withDO(c.DO.Debug())
}

func (c cashConvertersFilterDo) WithContext(ctx context.Context) ICashConvertersFilterDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cashConvertersFilterDo) ReadDB() ICashConvertersFilterDo {
	return c.Clauses(dbresolver.Read)
}

func (c cashConvertersFilterDo) WriteDB() ICashConvertersFilterDo {
	return c.Clauses(dbresolver.Write)
}

func (c cashConvertersFilterDo) Session(config *gorm.Session) ICashConvertersFilterDo {
	return c.withDO(c.DO.Session(config))
}

func (c cashConvertersFilterDo) Clauses(conds ...clause.Expression) ICashConvertersFilterDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cashConvertersFilterDo) Returning(value interface{}, columns ...string) ICashConvertersFilterDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cashConvertersFilterDo) Not(conds ...gen.Condition) ICashConvertersFilterDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cashConvertersFilterDo) Or(conds ...gen.Condition) ICashConvertersFilterDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cashConvertersFilterDo) Select(conds ...field.Expr) ICashConvertersFilterDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cashConvertersFilterDo) Where(conds ...gen.Condition) ICashConvertersFilterDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cashConvertersFilterDo) Order(conds ...field.Expr) ICashConvertersFilterDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cashConvertersFilterDo) Distinct(cols ...field.Expr) ICashConvertersFilterDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cashConvertersFilterDo) Omit(cols ...field.Expr) ICashConvertersFilterDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cashConvertersFilterDo) Join(table schema.Tabler, on ...field.Expr) ICashConvertersFilterDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cashConvertersFilterDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICashConvertersFilterDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cashConvertersFilterDo) RightJoin(table schema.Tabler, on ...field.Expr) ICashConvertersFilterDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cashConvertersFilterDo) Group(cols ...field.Expr) ICashConvertersFilterDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cashConvertersFilterDo) Having(conds ...gen.Condition) ICashConvertersFilterDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cashConvertersFilterDo) Limit(limit int) ICashConvertersFilterDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cashConvertersFilterDo) Offset(offset int) ICashConvertersFilterDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cashConvertersFilterDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICashConvertersFilterDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cashConvertersFilterDo) Unscoped() ICashConvertersFilterDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cashConvertersFilterDo) Create(values ...*models.CashConvertersFilter) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cashConvertersFilterDo) CreateInBatches(values []*models.CashConvertersFilter, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cashConvertersFilterDo) Save(values ...*models.CashConvertersFilter) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cashConvertersFilterDo) First() (*models.CashConvertersFilter, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.CashConvertersFilter), nil
	}
}

func (c cashConvertersFilterDo) Take() (*models.CashConvertersFilter, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.CashConvertersFilter), nil
	}
}

func (c cashConvertersFilterDo) Last() (*models.CashConvertersFilter, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.CashConvertersFilter), nil
	}
}

func (c cashConvertersFilterDo) Find() ([]*models.CashConvertersFilter, error) {
	result, err := c.DO.Find()
	return result.([]*models.CashConvertersFilter), err
}

func (c cashConvertersFilterDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.CashConvertersFilter, err error) {
	buf := make([]*models.CashConvertersFilter, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cashConvertersFilterDo) FindInBatches(result *[]*models.CashConvertersFilter, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cashConvertersFilterDo) Attrs(attrs ...field.AssignExpr) ICashConvertersFilterDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cashConvertersFilterDo) Assign(attrs ...field.AssignExpr) ICashConvertersFilterDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cashConvertersFilterDo) Joins(fields ...field.RelationField) ICashConvertersFilterDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cashConvertersFilterDo) Preload(fields ...field.RelationField) ICashConvertersFilterDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cashConvertersFilterDo) FirstOrInit() (*models.CashConvertersFilter, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.CashConvertersFilter), nil
	}
}

func (c cashConvertersFilterDo) FirstOrCreate() (*models.CashConvertersFilter, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.CashConvertersFilter), nil
	}
}

func (c cashConvertersFilterDo) FindByPage(offset int, limit int) (result []*models.CashConvertersFilter, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cashConvertersFilterDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cashConvertersFilterDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cashConvertersFilterDo) Delete(models ...*models.CashConvertersFilter) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cashConvertersFilterDo) withDO(do gen.Dao) *cashConvertersFilterDo {
	c.DO = *do.(*gen.DO)
	return c
}
