// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"dealscanner/internal/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newCsMarket(db *gorm.DB, opts ...gen.DOOption) csMarket {
	_csMarket := csMarket{}

	_csMarket.csMarketDo.UseDB(db, opts...)
	_csMarket.csMarketDo.UseModel(&models.CsMarket{})

	tableName := _csMarket.csMarketDo.TableName()
	_csMarket.ALL = field.NewAsterisk(tableName)
	_csMarket.Url = field.NewString(tableName, "url")
	_csMarket.DisplayUrl = field.NewString(tableName, "displayUrl")
	_csMarket.MaxPrice = field.NewFloat64(tableName, "maxPrice")
	_csMarket.MaxFloat = field.NewFloat64(tableName, "maxFloat")
	_csMarket.LastPrice = field.NewFloat64(tableName, "lastPrice")
	_csMarket.QueryId = field.NewString(tableName, "queryId")
	_csMarket.Query = csMarketBelongsToQuery{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Query", "models.SearchQuery"),
	}

	_csMarket.fillFieldMap()

	return _csMarket
}

type csMarket struct {
	csMarketDo csMarketDo

	ALL        field.Asterisk
	Url        field.String
	DisplayUrl field.String
	MaxPrice   field.Float64
	MaxFloat   field.Float64
	LastPrice  field.Float64
	QueryId    field.String
	Query      csMarketBelongsToQuery

	fieldMap map[string]field.Expr
}

func (c csMarket) Table(newTableName string) *csMarket {
	c.csMarketDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c csMarket) As(alias string) *csMarket {
	c.csMarketDo.DO = *(c.csMarketDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *csMarket) updateTableName(table string) *csMarket {
	c.ALL = field.NewAsterisk(table)
	c.Url = field.NewString(table, "url")
	c.DisplayUrl = field.NewString(table, "displayUrl")
	c.MaxPrice = field.NewFloat64(table, "maxPrice")
	c.MaxFloat = field.NewFloat64(table, "maxFloat")
	c.LastPrice = field.NewFloat64(table, "lastPrice")
	c.QueryId = field.NewString(table, "queryId")

	c.fillFieldMap()

	return c
}

func (c *csMarket) WithContext(ctx context.Context) ICsMarketDo { return c.csMarketDo.WithContext(ctx) }

func (c csMarket) TableName() string { return c.csMarketDo.TableName() }

func (c csMarket) Alias() string { return c.csMarketDo.Alias() }

func (c csMarket) Columns(cols ...field.Expr) gen.Columns { return c.csMarketDo.Columns(cols...) }

func (c *csMarket) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *csMarket) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 7)
	c.fieldMap["url"] = c.Url
	c.fieldMap["displayUrl"] = c.DisplayUrl
	c.fieldMap["maxPrice"] = c.MaxPrice
	c.fieldMap["maxFloat"] = c.MaxFloat
	c.fieldMap["lastPrice"] = c.LastPrice
	c.fieldMap["queryId"] = c.QueryId

}

func (c csMarket) clone(db *gorm.DB) csMarket {
	c.csMarketDo.ReplaceConnPool(db.Statement.ConnPool)
	c.Query.db = db.Session(&gorm.Session{Initialized: true})
	c.Query.db.Statement.ConnPool = db.Statement.ConnPool
	return c
}

func (c csMarket) replaceDB(db *gorm.DB) csMarket {
	c.csMarketDo.ReplaceDB(db)
	c.Query.db = db.Session(&gorm.Session{})
	return c
}

type csMarketBelongsToQuery struct {
	db *gorm.DB

	field.RelationField
}

func (a csMarketBelongsToQuery) Where(conds ...field.Expr) *csMarketBelongsToQuery {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a csMarketBelongsToQuery) WithContext(ctx context.Context) *csMarketBelongsToQuery {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a csMarketBelongsToQuery) Session(session *gorm.Session) *csMarketBelongsToQuery {
	a.db = a.db.Session(session)
	return &a
}

func (a csMarketBelongsToQuery) Model(m *models.CsMarket) *csMarketBelongsToQueryTx {
	return &csMarketBelongsToQueryTx{a.db.Model(m).Association(a.Name())}
}

func (a csMarketBelongsToQuery) Unscoped() *csMarketBelongsToQuery {
	a.db = a.db.Unscoped()
	return &a
}

type csMarketBelongsToQueryTx struct{ tx *gorm.Association }

func (a csMarketBelongsToQueryTx) Find() (result *models.SearchQuery, err error) {
	return result, a.tx.Find(&result)
}

func (a csMarketBelongsToQueryTx) Append(values ...*models.SearchQuery) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a csMarketBelongsToQueryTx) Replace(values ...*models.SearchQuery) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a csMarketBelongsToQueryTx) Delete(values ...*models.SearchQuery) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a csMarketBelongsToQueryTx) Clear() error {
	return a.tx.Clear()
}

func (a csMarketBelongsToQueryTx) Count() int64 {
	return a.tx.Count()
}

func (a csMarketBelongsToQueryTx) Unscoped() *csMarketBelongsToQueryTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type csMarketDo struct{ gen.DO }

type ICsMarketDo interface {
	gen.SubQuery
	Debug() ICsMarketDo
	WithContext(ctx context.Context) ICsMarketDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICsMarketDo
	WriteDB() ICsMarketDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICsMarketDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICsMarketDo
	Not(conds ...gen.Condition) ICsMarketDo
	Or(conds ...gen.Condition) ICsMarketDo
	Select(conds ...field.Expr) ICsMarketDo
	Where(conds ...gen.Condition) ICsMarketDo
	Order(conds ...field.Expr) ICsMarketDo
	Distinct(cols ...field.Expr) ICsMarketDo
	Omit(cols ...field.Expr) ICsMarketDo
	Join(table schema.Tabler, on ...field.Expr) ICsMarketDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICsMarketDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICsMarketDo
	Group(cols ...field.Expr) ICsMarketDo
	Having(conds ...gen.Condition) ICsMarketDo
	Limit(limit int) ICsMarketDo
	Offset(offset int) ICsMarketDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICsMarketDo
	Unscoped() ICsMarketDo
	Create(values ...*models.CsMarket) error
	CreateInBatches(values []*models.CsMarket, batchSize int) error
	Save(values ...*models.CsMarket) error
	First() (*models.CsMarket, error)
	Take() (*models.CsMarket, error)
	Last() (*models.CsMarket, error)
	Find() ([]*models.CsMarket, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.CsMarket, err error)
	FindInBatches(result *[]*models.CsMarket, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.CsMarket) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICsMarketDo
	Assign(attrs ...field.AssignExpr) ICsMarketDo
	Joins(fields ...field.RelationField) ICsMarketDo
	Preload(fields ...field.RelationField) ICsMarketDo
	FirstOrInit() (*models.CsMarket, error)
	FirstOrCreate() (*models.CsMarket, error)
	FindByPage(offset int, limit int) (result []*models.CsMarket, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICsMarketDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c csMarketDo) Debug() ICsMarketDo {
	return c.withDO(c.DO.Debug())
}

func (c csMarketDo) WithContext(ctx context.Context) ICsMarketDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c csMarketDo) ReadDB() ICsMarketDo {
	return c.Clauses(dbresolver.Read)
}

func (c csMarketDo) WriteDB() ICsMarketDo {
	return c.Clauses(dbresolver.Write)
}

func (c csMarketDo) Session(config *gorm.Session) ICsMarketDo {
	return c.withDO(c.DO.Session(config))
}

func (c csMarketDo) Clauses(conds ...clause.Expression) ICsMarketDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c csMarketDo) Returning(value interface{}, columns ...string) ICsMarketDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c csMarketDo) Not(conds ...gen.Condition) ICsMarketDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c csMarketDo) Or(conds ...gen.Condition) ICsMarketDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c csMarketDo) Select(conds ...field.Expr) ICsMarketDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c csMarketDo) Where(conds ...gen.Condition) ICsMarketDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c csMarketDo) Order(conds ...field.Expr) ICsMarketDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c csMarketDo) Distinct(cols ...field.Expr) ICsMarketDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c csMarketDo) Omit(cols ...field.Expr) ICsMarketDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c csMarketDo) Join(table schema.Tabler, on ...field.Expr) ICsMarketDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c csMarketDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICsMarketDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c csMarketDo) RightJoin(table schema.Tabler, on ...field.Expr) ICsMarketDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c csMarketDo) Group(cols ...field.Expr) ICsMarketDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c csMarketDo) Having(conds ...gen.Condition) ICsMarketDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c csMarketDo) Limit(limit int) ICsMarketDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c csMarketDo) Offset(offset int) ICsMarketDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c csMarketDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICsMarketDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c csMarketDo) Unscoped() ICsMarketDo {
	return c.withDO(c.DO.Unscoped())
}

func (c csMarketDo) Create(values ...*models.CsMarket) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c csMarketDo) CreateInBatches(values []*models.CsMarket, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c csMarketDo) Save(values ...*models.CsMarket) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c csMarketDo) First() (*models.CsMarket, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.CsMarket), nil
	}
}

func (c csMarketDo) Take() (*models.CsMarket, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.CsMarket), nil
	}
}

func (c csMarketDo) Last() (*models.CsMarket, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.CsMarket), nil
	}
}

func (c csMarketDo) Find() ([]*models.CsMarket, error) {
	result, err := c.DO.Find()
	return result.([]*models.CsMarket), err
}

func (c csMarketDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.CsMarket, err error) {
	buf := make([]*models.CsMarket, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c csMarketDo) FindInBatches(result *[]*models.CsMarket, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c csMarketDo) Attrs(attrs ...field.AssignExpr) ICsMarketDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c csMarketDo) Assign(attrs ...field.AssignExpr) ICsMarketDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c csMarketDo) Joins(fields ...field.RelationField) ICsMarketDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c csMarketDo) Preload(fields ...field.RelationField) ICsMarketDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c csMarketDo) FirstOrInit() (*models.CsMarket, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.CsMarket), nil
	}
}

func (c csMarketDo) FirstOrCreate() (*models.CsMarket, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.CsMarket), nil
	}
}

func (c csMarketDo) FindByPage(offset int, limit int) (result []*models.CsMarket, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c csMarketDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c csMarketDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c csMarketDo) Delete(models ...*models.CsMarket) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *csMarketDo) withDO(do gen.Dao) *csMarketDo {
	c.DO = *do.(*gen.DO)
	return c
}
