// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"dealscanner/internal/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newCsTradeBot(db *gorm.DB, opts ...gen.DOOption) csTradeBot {
	_csTradeBot := csTradeBot{}

	_csTradeBot.csTradeBotDo.UseDB(db, opts...)
	_csTradeBot.csTradeBotDo.UseModel(&models.CsTradeBot{})

	tableName := _csTradeBot.csTradeBotDo.TableName()
	_csTradeBot.ALL = field.NewAsterisk(tableName)
	_csTradeBot.Name = field.NewString(tableName, "name")
	_csTradeBot.MaxPrice = field.NewFloat64(tableName, "maxPrice")
	_csTradeBot.MinFloat = field.NewFloat64(tableName, "minFloat")
	_csTradeBot.MaxFloat = field.NewFloat64(tableName, "maxFloat")
	_csTradeBot.QueryId = field.NewString(tableName, "queryId")
	_csTradeBot.Query = csTradeBotBelongsToQuery{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Query", "models.SearchQuery"),
	}

	_csTradeBot.fillFieldMap()

	return _csTradeBot
}

type csTradeBot struct {
	csTradeBotDo csTradeBotDo

	ALL      field.Asterisk
	Name     field.String
	MaxPrice field.Float64
	MinFloat field.Float64
	MaxFloat field.Float64
	QueryId  field.String
	Query    csTradeBotBelongsToQuery

	fieldMap map[string]field.Expr
}

func (c csTradeBot) Table(newTableName string) *csTradeBot {
	c.csTradeBotDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c csTradeBot) As(alias string) *csTradeBot {
	c.csTradeBotDo.DO = *(c.csTradeBotDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *csTradeBot) updateTableName(table string) *csTradeBot {
	c.ALL = field.NewAsterisk(table)
	c.Name = field.NewString(table, "name")
	c.MaxPrice = field.NewFloat64(table, "maxPrice")
	c.MinFloat = field.NewFloat64(table, "minFloat")
	c.MaxFloat = field.NewFloat64(table, "maxFloat")
	c.QueryId = field.NewString(table, "queryId")

	c.fillFieldMap()

	return c
}

func (c *csTradeBot) WithContext(ctx context.Context) ICsTradeBotDo {
	return c.csTradeBotDo.WithContext(ctx)
}

func (c csTradeBot) TableName() string { return c.csTradeBotDo.TableName() }

func (c csTradeBot) Alias() string { return c.csTradeBotDo.Alias() }

func (c csTradeBot) Columns(cols ...field.Expr) gen.Columns { return c.csTradeBotDo.Columns(cols...) }

func (c *csTradeBot) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *csTradeBot) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 6)
	c.fieldMap["name"] = c.Name
	c.fieldMap["maxPrice"] = c.MaxPrice
	c.fieldMap["minFloat"] = c.MinFloat
	c.fieldMap["maxFloat"] = c.MaxFloat
	c.fieldMap["queryId"] = c.QueryId

}

func (c csTradeBot) clone(db *gorm.DB) csTradeBot {
	c.csTradeBotDo.ReplaceConnPool(db.Statement.ConnPool)
	c.Query.db = db.Session(&gorm.Session{Initialized: true})
	c.Query.db.Statement.ConnPool = db.Statement.ConnPool
	return c
}

func (c csTradeBot) replaceDB(db *gorm.DB) csTradeBot {
	c.csTradeBotDo.ReplaceDB(db)
	c.Query.db = db.Session(&gorm.Session{})
	return c
}

type csTradeBotBelongsToQuery struct {
	db *gorm.DB

	field.RelationField
}

func (a csTradeBotBelongsToQuery) Where(conds ...field.Expr) *csTradeBotBelongsToQuery {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a csTradeBotBelongsToQuery) WithContext(ctx context.Context) *csTradeBotBelongsToQuery {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a csTradeBotBelongsToQuery) Session(session *gorm.Session) *csTradeBotBelongsToQuery {
	a.db = a.db.Session(session)
	return &a
}

func (a csTradeBotBelongsToQuery) Model(m *models.CsTradeBot) *csTradeBotBelongsToQueryTx {
	return &csTradeBotBelongsToQueryTx{a.db.Model(m).Association(a.Name())}
}

func (a csTradeBotBelongsToQuery) Unscoped() *csTradeBotBelongsToQuery {
	a.db = a.db.Unscoped()
	return &a
}

type csTradeBotBelongsToQueryTx struct{ tx *gorm.Association }

func (a csTradeBotBelongsToQueryTx) Find() (result *models.SearchQuery, err error) {
	return result, a.tx.Find(&result)
}

func (a csTradeBotBelongsToQueryTx) Append(values ...*models.SearchQuery) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a csTradeBotBelongsToQueryTx) Replace(values ...*models.SearchQuery) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a csTradeBotBelongsToQueryTx) Delete(values ...*models.SearchQuery) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a csTradeBotBelongsToQueryTx) Clear() error {
	return a.tx.Clear()
}

func (a csTradeBotBelongsToQueryTx) Count() int64 {
	return a.tx.Count()
}

func (a csTradeBotBelongsToQueryTx) Unscoped() *csTradeBotBelongsToQueryTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type csTradeBotDo struct{ gen.DO }

type ICsTradeBotDo interface {
	gen.SubQuery
	Debug() ICsTradeBotDo
	WithContext(ctx context.Context) ICsTradeBotDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICsTradeBotDo
	WriteDB() ICsTradeBotDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICsTradeBotDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICsTradeBotDo
	Not(conds ...gen.Condition) ICsTradeBotDo
	Or(conds ...gen.Condition) ICsTradeBotDo
	Select(conds ...field.Expr) ICsTradeBotDo
	Where(conds ...gen.Condition) ICsTradeBotDo
	Order(conds ...field.Expr) ICsTradeBotDo
	Distinct(cols ...field.Expr) ICsTradeBotDo
	Omit(cols ...field.Expr) ICsTradeBotDo
	Join(table schema.Tabler, on ...field.Expr) ICsTradeBotDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICsTradeBotDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICsTradeBotDo
	Group(cols ...field.Expr) ICsTradeBotDo
	Having(conds ...gen.Condition) ICsTradeBotDo
	Limit(limit int) ICsTradeBotDo
	Offset(offset int) ICsTradeBotDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICsTradeBotDo
	Unscoped() ICsTradeBotDo
	Create(values ...*models.CsTradeBot) error
	CreateInBatches(values []*models.CsTradeBot, batchSize int) error
	Save(values ...*models.CsTradeBot) error
	First() (*models.CsTradeBot, error)
	Take() (*models.CsTradeBot, error)
	Last() (*models.CsTradeBot, error)
	Find() ([]*models.CsTradeBot, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.CsTradeBot, err error)
	FindInBatches(result *[]*models.CsTradeBot, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.CsTradeBot) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICsTradeBotDo
	Assign(attrs ...field.AssignExpr) ICsTradeBotDo
	Joins(fields ...field.RelationField) ICsTradeBotDo
	Preload(fields ...field.RelationField) ICsTradeBotDo
	FirstOrInit() (*models.CsTradeBot, error)
	FirstOrCreate() (*models.CsTradeBot, error)
	FindByPage(offset int, limit int) (result []*models.CsTradeBot, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICsTradeBotDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c csTradeBotDo) Debug() ICsTradeBotDo {
	return c.withDO(c.DO.Debug())
}

func (c csTradeBotDo) WithContext(ctx context.Context) ICsTradeBotDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c csTradeBotDo) ReadDB() ICsTradeBotDo {
	return c.Clauses(dbresolver.Read)
}

func (c csTradeBotDo) WriteDB() ICsTradeBotDo {
	return c.Clauses(dbresolver.Write)
}

func (c csTradeBotDo) Session(config *gorm.Session) ICsTradeBotDo {
	return c.withDO(c.DO.Session(config))
}

func (c csTradeBotDo) Clauses(conds ...clause.Expression) ICsTradeBotDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c csTradeBotDo) Returning(value interface{}, columns ...string) ICsTradeBotDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c csTradeBotDo) Not(conds ...gen.Condition) ICsTradeBotDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c csTradeBotDo) Or(conds ...gen.Condition) ICsTradeBotDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c csTradeBotDo) Select(conds ...field.Expr) ICsTradeBotDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c csTradeBotDo) Where(conds ...gen.Condition) ICsTradeBotDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c csTradeBotDo) Order(conds ...field.Expr) ICsTradeBotDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c csTradeBotDo) Distinct(cols ...field.Expr) ICsTradeBotDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c csTradeBotDo) Omit(cols ...field.Expr) ICsTradeBotDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c csTradeBotDo) Join(table schema.Tabler, on ...field.Expr) ICsTradeBotDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c csTradeBotDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICsTradeBotDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c csTradeBotDo) RightJoin(table schema.Tabler, on ...field.Expr) ICsTradeBotDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c csTradeBotDo) Group(cols ...field.Expr) ICsTradeBotDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c csTradeBotDo) Having(conds ...gen.Condition) ICsTradeBotDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c csTradeBotDo) Limit(limit int) ICsTradeBotDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c csTradeBotDo) Offset(offset int) ICsTradeBotDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c csTradeBotDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICsTradeBotDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c csTradeBotDo) Unscoped() ICsTradeBotDo {
	return c.withDO(c.DO.Unscoped())
}

func (c csTradeBotDo) Create(values ...*models.CsTradeBot) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c csTradeBotDo) CreateInBatches(values []*models.CsTradeBot, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c csTradeBotDo) Save(values ...*models.CsTradeBot) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c csTradeBotDo) First() (*models.CsTradeBot, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.CsTradeBot), nil
	}
}

func (c csTradeBotDo) Take() (*models.CsTradeBot, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.CsTradeBot), nil
	}
}

func (c csTradeBotDo) Last() (*models.CsTradeBot, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.CsTradeBot), nil
	}
}

func (c csTradeBotDo) Find() ([]*models.CsTradeBot, error) {
	result, err := c.DO.Find()
	return result.([]*models.CsTradeBot), err
}

func (c csTradeBotDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.CsTradeBot, err error) {
	buf := make([]*models.CsTradeBot, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c csTradeBotDo) FindInBatches(result *[]*models.CsTradeBot, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c csTradeBotDo) Attrs(attrs ...field.AssignExpr) ICsTradeBotDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c csTradeBotDo) Assign(attrs ...field.AssignExpr) ICsTradeBotDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c csTradeBotDo) Joins(fields ...field.RelationField) ICsTradeBotDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c csTradeBotDo) Preload(fields ...field.RelationField) ICsTradeBotDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c csTradeBotDo) FirstOrInit() (*models.CsTradeBot, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.CsTradeBot), nil
	}
}

func (c csTradeBotDo) FirstOrCreate() (*models.CsTradeBot, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.CsTradeBot), nil
	}
}

func (c csTradeBotDo) FindByPage(offset int, limit int) (result []*models.CsTradeBot, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c csTradeBotDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c csTradeBotDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c csTradeBotDo) Delete(models ...*models.CsTradeBot) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *csTradeBotDo) withDO(do gen.Dao) *csTradeBotDo {
	c.DO = *do.(*gen.DO)
	return c
}
