// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"dealscanner/internal/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newEbay(db *gorm.DB, opts ...gen.DOOption) ebay {
	_ebay := ebay{}

	_ebay.ebayDo.UseDB(db, opts...)
	_ebay.ebayDo.UseModel(&models.Ebay{})

	tableName := _ebay.ebayDo.TableName()
	_ebay.ALL = field.NewAsterisk(tableName)
	_ebay.Url = field.NewString(tableName, "url")
	_ebay.MaxPrice = field.NewFloat64(tableName, "maxPrice")
	_ebay.QueryId = field.NewString(tableName, "queryId")
	_ebay.Query = ebayBelongsToQuery{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Query", "models.SearchQuery"),
	}

	_ebay.fillFieldMap()

	return _ebay
}

type ebay struct {
	ebayDo ebayDo

	ALL      field.Asterisk
	Url      field.String
	MaxPrice field.Float64
	QueryId  field.String
	Query    ebayBelongsToQuery

	fieldMap map[string]field.Expr
}

func (e ebay) Table(newTableName string) *ebay {
	e.ebayDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e ebay) As(alias string) *ebay {
	e.ebayDo.DO = *(e.ebayDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *ebay) updateTableName(table string) *ebay {
	e.ALL = field.NewAsterisk(table)
	e.Url = field.NewString(table, "url")
	e.MaxPrice = field.NewFloat64(table, "maxPrice")
	e.QueryId = field.NewString(table, "queryId")

	e.fillFieldMap()

	return e
}

func (e *ebay) WithContext(ctx context.Context) IEbayDo { return e.ebayDo.WithContext(ctx) }

func (e ebay) TableName() string { return e.ebayDo.TableName() }

func (e ebay) Alias() string { return e.ebayDo.Alias() }

func (e ebay) Columns(cols ...field.Expr) gen.Columns { return e.ebayDo.Columns(cols...) }

func (e *ebay) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *ebay) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 4)
	e.fieldMap["url"] = e.Url
	e.fieldMap["maxPrice"] = e.MaxPrice
	e.fieldMap["queryId"] = e.QueryId

}

func (e ebay) clone(db *gorm.DB) ebay {
	e.ebayDo.ReplaceConnPool(db.Statement.ConnPool)
	e.Query.db = db.Session(&gorm.Session{Initialized: true})
	e.Query.db.Statement.ConnPool = db.Statement.ConnPool
	return e
}

func (e ebay) replaceDB(db *gorm.DB) ebay {
	e.ebayDo.ReplaceDB(db)
	e.Query.db = db.Session(&gorm.Session{})
	return e
}

type ebayBelongsToQuery struct {
	db *gorm.DB

	field.RelationField
}

func (a ebayBelongsToQuery) Where(conds ...field.Expr) *ebayBelongsToQuery {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a ebayBelongsToQuery) WithContext(ctx context.Context) *ebayBelongsToQuery {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a ebayBelongsToQuery) Session(session *gorm.Session) *ebayBelongsToQuery {
	a.db = a.db.Session(session)
	return &a
}

func (a ebayBelongsToQuery) Model(m *models.Ebay) *ebayBelongsToQueryTx {
	return &ebayBelongsToQueryTx{a.db.Model(m).Association(a.Name())}
}

func (a ebayBelongsToQuery) Unscoped() *ebayBelongsToQuery {
	a.db = a.db.Unscoped()
	return &a
}

type ebayBelongsToQueryTx struct{ tx *gorm.Association }

func (a ebayBelongsToQueryTx) Find() (result *models.SearchQuery, err error) {
	return result, a.tx.Find(&result)
}

func (a ebayBelongsToQueryTx) Append(values ...*models.SearchQuery) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a ebayBelongsToQueryTx) Replace(values ...*models.SearchQuery) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a ebayBelongsToQueryTx) Delete(values ...*models.SearchQuery) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a ebayBelongsToQueryTx) Clear() error {
	return a.tx.Clear()
}

func (a ebayBelongsToQueryTx) Count() int64 {
	return a.tx.Count()
}

func (a ebayBelongsToQueryTx) Unscoped() *ebayBelongsToQueryTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type ebayDo struct{ gen.DO }

type IEbayDo interface {
	gen.SubQuery
	Debug() IEbayDo
	WithContext(ctx context.Context) IEbayDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IEbayDo
	WriteDB() IEbayDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IEbayDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IEbayDo
	Not(conds ...gen.Condition) IEbayDo
	Or(conds ...gen.Condition) IEbayDo
	Select(conds ...field.Expr) IEbayDo
	Where(conds ...gen.Condition) IEbayDo
	Order(conds ...field.Expr) IEbayDo
	Distinct(cols ...field.Expr) IEbayDo
	Omit(cols ...field.Expr) IEbayDo
	Join(table schema.Tabler, on ...field.Expr) IEbayDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IEbayDo
	RightJoin(table schema.Tabler, on ...field.Expr) IEbayDo
	Group(cols ...field.Expr) IEbayDo
	Having(conds ...gen.Condition) IEbayDo
	Limit(limit int) IEbayDo
	Offset(offset int) IEbayDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IEbayDo
	Unscoped() IEbayDo
	Create(values ...*models.Ebay) error
	CreateInBatches(values []*models.Ebay, batchSize int) error
	Save(values ...*models.Ebay) error
	First() (*models.Ebay, error)
	Take() (*models.Ebay, error)
	Last() (*models.Ebay, error)
	Find() ([]*models.Ebay, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Ebay, err error)
	FindInBatches(result *[]*models.Ebay, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Ebay) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IEbayDo
	Assign(attrs ...field.AssignExpr) IEbayDo
	Joins(fields ...field.RelationField) IEbayDo
	Preload(fields ...field.RelationField) IEbayDo
	FirstOrInit() (*models.Ebay, error)
	FirstOrCreate() (*models.Ebay, error)
	FindByPage(offset int, limit int) (result []*models.Ebay, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IEbayDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (e ebayDo) Debug() IEbayDo {
	return e.withDO(e.DO.Debug())
}

func (e ebayDo) WithContext(ctx context.Context) IEbayDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e ebayDo) ReadDB() IEbayDo {
	return e.Clauses(dbresolver.Read)
}

func (e ebayDo) WriteDB() IEbayDo {
	return e.Clauses(dbresolver.Write)
}

func (e ebayDo) Session(config *gorm.Session) IEbayDo {
	return e.withDO(e.DO.Session(config))
}

func (e ebayDo) Clauses(conds ...clause.Expression) IEbayDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e ebayDo) Returning(value interface{}, columns ...string) IEbayDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e ebayDo) Not(conds ...gen.Condition) IEbayDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e ebayDo) Or(conds ...gen.Condition) IEbayDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e ebayDo) Select(conds ...field.Expr) IEbayDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e ebayDo) Where(conds ...gen.Condition) IEbayDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e ebayDo) Order(conds ...field.Expr) IEbayDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e ebayDo) Distinct(cols ...field.Expr) IEbayDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e ebayDo) Omit(cols ...field.Expr) IEbayDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e ebayDo) Join(table schema.Tabler, on ...field.Expr) IEbayDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e ebayDo) LeftJoin(table schema.Tabler, on ...field.Expr) IEbayDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e ebayDo) RightJoin(table schema.Tabler, on ...field.Expr) IEbayDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e ebayDo) Group(cols ...field.Expr) IEbayDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e ebayDo) Having(conds ...gen.Condition) IEbayDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e ebayDo) Limit(limit int) IEbayDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e ebayDo) Offset(offset int) IEbayDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e ebayDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IEbayDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e ebayDo) Unscoped() IEbayDo {
	return e.withDO(e.DO.Unscoped())
}

func (e ebayDo) Create(values ...*models.Ebay) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e ebayDo) CreateInBatches(values []*models.Ebay, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e ebayDo) Save(values ...*models.Ebay) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e ebayDo) First() (*models.Ebay, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Ebay), nil
	}
}

func (e ebayDo) Take() (*models.Ebay, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Ebay), nil
	}
}

func (e ebayDo) Last() (*models.Ebay, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Ebay), nil
	}
}

func (e ebayDo) Find() ([]*models.Ebay, error) {
	result, err := e.DO.Find()
	return result.([]*models.Ebay), err
}

func (e ebayDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Ebay, err error) {
	buf := make([]*models.Ebay, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e ebayDo) FindInBatches(result *[]*models.Ebay, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e ebayDo) Attrs(attrs ...field.AssignExpr) IEbayDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e ebayDo) Assign(attrs ...field.AssignExpr) IEbayDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e ebayDo) Joins(fields ...field.RelationField) IEbayDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e ebayDo) Preload(fields ...field.RelationField) IEbayDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e ebayDo) FirstOrInit() (*models.Ebay, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Ebay), nil
	}
}

func (e ebayDo) FirstOrCreate() (*models.Ebay, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Ebay), nil
	}
}

func (e ebayDo) FindByPage(offset int, limit int) (result []*models.Ebay, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e ebayDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e ebayDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e ebayDo) Delete(models ...*models.Ebay) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *ebayDo) withDO(do gen.Dao) *ebayDo {
	e.DO = *do.(*gen.DO)
	return e
}
