// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                    = new(Query)
	ActionRegistry       *actionRegistry
	CashConverters       *cashConverters
	CashConvertersFilter *cashConvertersFilter
	CsMarket             *csMarket
	CsTradeBot           *csTradeBot
	Ebay                 *ebay
	Globals              *globals
	Gumtree              *gumtree
	Listing              *listing
	ListingObservation   *listingObservation
	QueryListingState    *queryListingState
	Salvos               *salvos
	ScannerRuntimeState  *scannerRuntimeState
	SearchQuery          *searchQuery
	SteamMarket          *steamMarket
	TtlItem              *ttlItem
	UserQuery            *userQuery
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	ActionRegistry = &Q.ActionRegistry
	CashConverters = &Q.CashConverters
	CashConvertersFilter = &Q.CashConvertersFilter
	CsMarket = &Q.CsMarket
	CsTradeBot = &Q.CsTradeBot
	Ebay = &Q.Ebay
	Globals = &Q.Globals
	Gumtree = &Q.Gumtree
	Listing = &Q.Listing
	ListingObservation = &Q.ListingObservation
	QueryListingState = &Q.QueryListingState
	Salvos = &Q.Salvos
	ScannerRuntimeState = &Q.ScannerRuntimeState
	SearchQuery = &Q.SearchQuery
	SteamMarket = &Q.SteamMarket
	TtlItem = &Q.TtlItem
	UserQuery = &Q.UserQuery
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                   db,
		ActionRegistry:       newActionRegistry(db, opts...),
		CashConverters:       newCashConverters(db, opts...),
		CashConvertersFilter: newCashConvertersFilter(db, opts...),
		CsMarket:             newCsMarket(db, opts...),
		CsTradeBot:           newCsTradeBot(db, opts...),
		Ebay:                 newEbay(db, opts...),
		Globals:              newGlobals(db, opts...),
		Gumtree:              newGumtree(db, opts...),
		Listing:              newListing(db, opts...),
		ListingObservation:   newListingObservation(db, opts...),
		QueryListingState:    newQueryListingState(db, opts...),
		Salvos:               newSalvos(db, opts...),
		ScannerRuntimeState:  newScannerRuntimeState(db, opts...),
		SearchQuery:          newSearchQuery(db, opts...),
		SteamMarket:          newSteamMarket(db, opts...),
		TtlItem:              newTtlItem(db, opts...),
		UserQuery:            newUserQuery(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	ActionRegistry       actionRegistry
	CashConverters       cashConverters
	CashConvertersFilter cashConvertersFilter
	CsMarket             csMarket
	CsTradeBot           csTradeBot
	Ebay                 ebay
	Globals              globals
	Gumtree              gumtree
	Listing              listing
	ListingObservation   listingObservation
	QueryListingState    queryListingState
	Salvos               salvos
	ScannerRuntimeState  scannerRuntimeState
	SearchQuery          searchQuery
	SteamMarket          steamMarket
	TtlItem              ttlItem
	UserQuery            userQuery
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                   db,
		ActionRegistry:       q.ActionRegistry.clone(db),
		CashConverters:       q.CashConverters.clone(db),
		CashConvertersFilter: q.CashConvertersFilter.clone(db),
		CsMarket:             q.CsMarket.clone(db),
		CsTradeBot:           q.CsTradeBot.clone(db),
		Ebay:                 q.Ebay.clone(db),
		Globals:              q.Globals.clone(db),
		Gumtree:              q.Gumtree.clone(db),
		Listing:              q.Listing.clone(db),
		ListingObservation:   q.ListingObservation.clone(db),
		QueryListingState:    q.QueryListingState.clone(db),
		Salvos:               q.Salvos.clone(db),
		ScannerRuntimeState:  q.ScannerRuntimeState.clone(db),
		SearchQuery:          q.SearchQuery.clone(db),
		SteamMarket:          q.SteamMarket.clone(db),
		TtlItem:              q.TtlItem.clone(db),
		UserQuery:            q.UserQuery.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                   db,
		ActionRegistry:       q.ActionRegistry.replaceDB(db),
		CashConverters:       q.CashConverters.replaceDB(db),
		CashConvertersFilter: q.CashConvertersFilter.replaceDB(db),
		CsMarket:             q.CsMarket.replaceDB(db),
		CsTradeBot:           q.CsTradeBot.replaceDB(db),
		Ebay:                 q.Ebay.replaceDB(db),
		Globals:              q.Globals.replaceDB(db),
		Gumtree:              q.Gumtree.replaceDB(db),
		Listing:              q.Listing.replaceDB(db),
		ListingObservation:   q.ListingObservation.replaceDB(db),
		QueryListingState:    q.QueryListingState.replaceDB(db),
		Salvos:               q.Salvos.replaceDB(db),
		ScannerRuntimeState:  q.ScannerRuntimeState.replaceDB(db),
		SearchQuery:          q.SearchQuery.replaceDB(db),
		SteamMarket:          q.SteamMarket.replaceDB(db),
		TtlItem:              q.TtlItem.replaceDB(db),
		UserQuery:            q.UserQuery.replaceDB(db),
	}
}

type queryCtx struct {
	ActionRegistry       IActionRegistryDo
	CashConverters       ICashConvertersDo
	CashConvertersFilter ICashConvertersFilterDo
	CsMarket             ICsMarketDo
	CsTradeBot           ICsTradeBotDo
	Ebay                 IEbayDo
	Globals              IGlobalsDo
	Gumtree              IGumtreeDo
	Listing              IListingDo
	ListingObservation   IListingObservationDo
	QueryListingState    IQueryListingStateDo
	Salvos               ISalvosDo
	ScannerRuntimeState  IScannerRuntimeStateDo
	SearchQuery          ISearchQueryDo
	SteamMarket          ISteamMarketDo
	TtlItem              ITtlItemDo
	UserQuery            IUserQueryDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		ActionRegistry:       q.ActionRegistry.WithContext(ctx),
		CashConverters:       q.CashConverters.WithContext(ctx),
		CashConvertersFilter: q.CashConvertersFilter.WithContext(ctx),
		CsMarket:             q.CsMarket.WithContext(ctx),
		CsTradeBot:           q.CsTradeBot.WithContext(ctx),
		Ebay:                 q.Ebay.WithContext(ctx),
		Globals:              q.Globals.WithContext(ctx),
		Gumtree:              q.Gumtree.WithContext(ctx),
		Listing:              q.Listing.WithContext(ctx),
		ListingObservation:   q.ListingObservation.WithContext(ctx),
		QueryListingState:    q.QueryListingState.WithContext(ctx),
		Salvos:               q.Salvos.WithContext(ctx),
		ScannerRuntimeState:  q.ScannerRuntimeState.WithContext(ctx),
		SearchQuery:          q.SearchQuery.WithContext(ctx),
		SteamMarket:          q.SteamMarket.WithContext(ctx),
		TtlItem:              q.TtlItem.WithContext(ctx),
		UserQuery:            q.UserQuery.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
