// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"dealscanner/internal/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newGlobals(db *gorm.DB, opts ...gen.DOOption) globals {
	_globals := globals{}

	_globals.globalsDo.UseDB(db, opts...)
	_globals.globalsDo.UseModel(&models.Globals{})

	tableName := _globals.globalsDo.TableName()
	_globals.ALL = field.NewAsterisk(tableName)
	_globals.ID = field.NewString(tableName, "id")
	_globals.BotClientId = field.NewString(tableName, "BOT_CLIENT_ID")
	_globals.CashConverters = field.NewBool(tableName, "CASH_CONVERTERS")
	_globals.CashConvertersChannelId = field.NewString(tableName, "CASH_CONVERTERS_CHANNEL_ID")
	_globals.CashConvertersRoleId = field.NewString(tableName, "CASH_CONVERTERS_ROLE_ID")
	_globals.CommandPermissionRoleId = field.NewString(tableName, "COMMAND_PERMISSION_ROLE_ID")
	_globals.CsChannelId = field.NewString(tableName, "CS_CHANNEL_ID")
	_globals.CsItems = field.NewBool(tableName, "CS_ITEMS")
	_globals.CsMarketChannelId = field.NewString(tableName, "CS_MARKET_CHANNEL_ID")
	_globals.CsMarketRoleId = field.NewString(tableName, "CS_MARKET_ROLE_ID")
	_globals.CsRoleId = field.NewString(tableName, "CS_ROLE_ID")
	_globals.DiscordGuildId = field.NewString(tableName, "DISCORD_GUILD_ID")
	_globals.DiscordToken = field.NewString(tableName, "DISCORD_TOKEN")
	_globals.Ebay = field.NewBool(tableName, "EBAY")
	_globals.EbayChannelId = field.NewString(tableName, "EBAY_CHANNEL_ID")
	_globals.EbayRoleId = field.NewString(tableName, "EBAY_ROLE_ID")
	_globals.ErrorChannelId = field.NewString(tableName, "ERROR_CHANNEL_ID")
	_globals.Gumtree = field.NewBool(tableName, "GUMTREE")
	_globals.GumtreeChannelId = field.NewString(tableName, "GUMTREE_CHANNEL_ID")
	_globals.GumtreeRoleId = field.NewString(tableName, "GUMTREE_ROLE_ID")
	_globals.Salvos = field.NewBool(tableName, "SALVOS")
	_globals.SalvosChannelId = field.NewString(tableName, "SALVOS_CHANNEL_ID")
	_globals.SalvosRoleId = field.NewString(tableName, "SALVOS_ROLE_ID")
	_globals.SteamQuery = field.NewBool(tableName, "STEAM_QUERY")
	_globals.SteamQueryChannelId = field.NewString(tableName, "STEAM_QUERY_CHANNEL_ID")
	_globals.SteamQueryRoleId = field.NewString(tableName, "STEAM_QUERY_ROLE_ID")
	_globals.CsTradeDollarRatio = field.NewFloat64(tableName, "CS_TRADE_DOLLAR_RATIO")
	_globals.LootFarmDollarRatio = field.NewFloat64(tableName, "LOOT_FARM_DOLLAR_RATIO")
	_globals.CsDealsDollarRatio = field.NewFloat64(tableName, "CS_DEALS_DOLLAR_RATIO")
	_globals.TradeitGgDollarRatio = field.NewFloat64(tableName, "TRADEIT_GG_DOLLAR_RATIO")

	_globals.fillFieldMap()

	return _globals
}

type globals struct {
	globalsDo globalsDo

	ALL                     field.Asterisk
	ID                      field.String
	BotClientId             field.String
	CashConverters          field.Bool
	CashConvertersChannelId field.String
	CashConvertersRoleId    field.String
	CommandPermissionRoleId field.String
	CsChannelId             field.String
	CsItems                 field.Bool
	CsMarketChannelId       field.String
	CsMarketRoleId          field.String
	CsRoleId                field.String
	DiscordGuildId          field.String
	DiscordToken            field.String
	Ebay                    field.Bool
	EbayChannelId           field.String
	EbayRoleId              field.String
	ErrorChannelId          field.String
	Gumtree                 field.Bool
	GumtreeChannelId        field.String
	GumtreeRoleId           field.String
	Salvos                  field.Bool
	SalvosChannelId         field.String
	SalvosRoleId            field.String
	SteamQuery              field.Bool
	SteamQueryChannelId     field.String
	SteamQueryRoleId        field.String
	CsTradeDollarRatio      field.Float64
	LootFarmDollarRatio     field.Float64
	CsDealsDollarRatio      field.Float64
	TradeitGgDollarRatio    field.Float64

	fieldMap map[string]field.Expr
}

func (g globals) Table(newTableName string) *globals {
	g.globalsDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g globals) As(alias string) *globals {
	g.globalsDo.DO = *(g.globalsDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *globals) updateTableName(table string) *globals {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewString(table, "id")
	g.BotClientId = field.NewString(table, "BOT_CLIENT_ID")
	g.CashConverters = field.NewBool(table, "CASH_CONVERTERS")
	g.CashConvertersChannelId = field.NewString(table, "CASH_CONVERTERS_CHANNEL_ID")
	g.CashConvertersRoleId = field.NewString(table, "CASH_CONVERTERS_ROLE_ID")
	g.CommandPermissionRoleId = field.NewString(table, "COMMAND_PERMISSION_ROLE_ID")
	g.CsChannelId = field.NewString(table, "CS_CHANNEL_ID")
	g.CsItems = field.NewBool(table, "CS_ITEMS")
	g.CsMarketChannelId = field.NewString(table, "CS_MARKET_CHANNEL_ID")
	g.CsMarketRoleId = field.NewString(table, "CS_MARKET_ROLE_ID")
	g.CsRoleId = field.NewString(table, "CS_ROLE_ID")
	g.DiscordGuildId = field.NewString(table, "DISCORD_GUILD_ID")
	g.DiscordToken = field.NewString(table, "DISCORD_TOKEN")
	g.Ebay = field.NewBool(table, "EBAY")
	g.EbayChannelId = field.NewString(table, "EBAY_CHANNEL_ID")
	g.EbayRoleId = field.NewString(table, "EBAY_ROLE_ID")
	g.ErrorChannelId = field.NewString(table, "ERROR_CHANNEL_ID")
	g.Gumtree = field.NewBool(table, "GUMTREE")
	g.GumtreeChannelId = field.NewString(table, "GUMTREE_CHANNEL_ID")
	g.GumtreeRoleId = field.NewString(table, "GUMTREE_ROLE_ID")
	g.Salvos = field.NewBool(table, "SALVOS")
	g.SalvosChannelId = field.NewString(table, "SALVOS_CHANNEL_ID")
	g.SalvosRoleId = field.NewString(table, "SALVOS_ROLE_ID")
	g.SteamQuery = field.NewBool(table, "STEAM_QUERY")
	g.SteamQueryChannelId = field.NewString(table, "STEAM_QUERY_CHANNEL_ID")
	g.SteamQueryRoleId = field.NewString(table, "STEAM_QUERY_ROLE_ID")
	g.CsTradeDollarRatio = field.NewFloat64(table, "CS_TRADE_DOLLAR_RATIO")
	g.LootFarmDollarRatio = field.NewFloat64(table, "LOOT_FARM_DOLLAR_RATIO")
	g.CsDealsDollarRatio = field.NewFloat64(table, "CS_DEALS_DOLLAR_RATIO")
	g.TradeitGgDollarRatio = field.NewFloat64(table, "TRADEIT_GG_DOLLAR_RATIO")

	g.fillFieldMap()

	return g
}

func (g *globals) WithContext(ctx context.Context) IGlobalsDo { return g.globalsDo.WithContext(ctx) }

func (g globals) TableName() string { return g.globalsDo.TableName() }

func (g globals) Alias() string { return g.globalsDo.Alias() }

func (g globals) Columns(cols ...field.Expr) gen.Columns { return g.globalsDo.Columns(cols...) }

func (g *globals) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *globals) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 30)
	g.fieldMap["id"] = g.ID
	g.fieldMap["BOT_CLIENT_ID"] = g.BotClientId
	g.fieldMap["CASH_CONVERTERS"] = g.CashConverters
	g.fieldMap["CASH_CONVERTERS_CHANNEL_ID"] = g.CashConvertersChannelId
	g.fieldMap["CASH_CONVERTERS_ROLE_ID"] = g.CashConvertersRoleId
	g.fieldMap["COMMAND_PERMISSION_ROLE_ID"] = g.CommandPermissionRoleId
	g.fieldMap["CS_CHANNEL_ID"] = g.CsChannelId
	g.fieldMap["CS_ITEMS"] = g.CsItems
	g.fieldMap["CS_MARKET_CHANNEL_ID"] = g.CsMarketChannelId
	g.fieldMap["CS_MARKET_ROLE_ID"] = g.CsMarketRoleId
	g.fieldMap["CS_ROLE_ID"] = g.CsRoleId
	g.fieldMap["DISCORD_GUILD_ID"] = g.DiscordGuildId
	g.fieldMap["DISCORD_TOKEN"] = g.DiscordToken
	g.fieldMap["EBAY"] = g.Ebay
	g.fieldMap["EBAY_CHANNEL_ID"] = g.EbayChannelId
	g.fieldMap["EBAY_ROLE_ID"] = g.EbayRoleId
	g.fieldMap["ERROR_CHANNEL_ID"] = g.ErrorChannelId
	g.fieldMap["GUMTREE"] = g.Gumtree
	g.fieldMap["GUMTREE_CHANNEL_ID"] = g.GumtreeChannelId
	g.fieldMap["GUMTREE_ROLE_ID"] = g.GumtreeRoleId
	g.fieldMap["SALVOS"] = g.Salvos
	g.fieldMap["SALVOS_CHANNEL_ID"] = g.SalvosChannelId
	g.fieldMap["SALVOS_ROLE_ID"] = g.SalvosRoleId
	g.fieldMap["STEAM_QUERY"] = g.SteamQuery
	g.fieldMap["STEAM_QUERY_CHANNEL_ID"] = g.SteamQueryChannelId
	g.fieldMap["STEAM_QUERY_ROLE_ID"] = g.SteamQueryRoleId
	g.fieldMap["CS_TRADE_DOLLAR_RATIO"] = g.CsTradeDollarRatio
	g.fieldMap["LOOT_FARM_DOLLAR_RATIO"] = g.LootFarmDollarRatio
	g.fieldMap["CS_DEALS_DOLLAR_RATIO"] = g.CsDealsDollarRatio
	g.fieldMap["TRADEIT_GG_DOLLAR_RATIO"] = g.TradeitGgDollarRatio
}

func (g globals) clone(db *gorm.DB) globals {
	g.globalsDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g globals) replaceDB(db *gorm.DB) globals {
	g.globalsDo.ReplaceDB(db)
	return g
}

type globalsDo struct{ gen.DO }

type IGlobalsDo interface {
	gen.SubQuery
	Debug() IGlobalsDo
	WithContext(ctx context.Context) IGlobalsDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IGlobalsDo
	WriteDB() IGlobalsDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IGlobalsDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IGlobalsDo
	Not(conds ...gen.Condition) IGlobalsDo
	Or(conds ...gen.Condition) IGlobalsDo
	Select(conds ...field.Expr) IGlobalsDo
	Where(conds ...gen.Condition) IGlobalsDo
	Order(conds ...field.Expr) IGlobalsDo
	Distinct(cols ...field.Expr) IGlobalsDo
	Omit(cols ...field.Expr) IGlobalsDo
	Join(table schema.Tabler, on ...field.Expr) IGlobalsDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IGlobalsDo
	RightJoin(table schema.Tabler, on ...field.Expr) IGlobalsDo
	Group(cols ...field.Expr) IGlobalsDo
	Having(conds ...gen.Condition) IGlobalsDo
	Limit(limit int) IGlobalsDo
	Offset(offset int) IGlobalsDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IGlobalsDo
	Unscoped() IGlobalsDo
	Create(values ...*models.Globals) error
	CreateInBatches(values []*models.Globals, batchSize int) error
	Save(values ...*models.Globals) error
	First() (*models.Globals, error)
	Take() (*models.Globals, error)
	Last() (*models.Globals, error)
	Find() ([]*models.Globals, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Globals, err error)
	FindInBatches(result *[]*models.Globals, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Globals) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IGlobalsDo
	Assign(attrs ...field.AssignExpr) IGlobalsDo
	Joins(fields ...field.RelationField) IGlobalsDo
	Preload(fields ...field.RelationField) IGlobalsDo
	FirstOrInit() (*models.Globals, error)
	FirstOrCreate() (*models.Globals, error)
	FindByPage(offset int, limit int) (result []*models.Globals, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IGlobalsDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (g globalsDo) Debug() IGlobalsDo {
	return g.withDO(g.DO.Debug())
}

func (g globalsDo) WithContext(ctx context.Context) IGlobalsDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g globalsDo) ReadDB() IGlobalsDo {
	return g.Clauses(dbresolver.Read)
}

func (g globalsDo) WriteDB() IGlobalsDo {
	return g.Clauses(dbresolver.Write)
}

func (g globalsDo) Session(config *gorm.Session) IGlobalsDo {
	return g.withDO(g.DO.Session(config))
}

func (g globalsDo) Clauses(conds ...clause.Expression) IGlobalsDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g globalsDo) Returning(value interface{}, columns ...string) IGlobalsDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g globalsDo) Not(conds ...gen.Condition) IGlobalsDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g globalsDo) Or(conds ...gen.Condition) IGlobalsDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g globalsDo) Select(conds ...field.Expr) IGlobalsDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g globalsDo) Where(conds ...gen.Condition) IGlobalsDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g globalsDo) Order(conds ...field.Expr) IGlobalsDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g globalsDo) Distinct(cols ...field.Expr) IGlobalsDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g globalsDo) Omit(cols ...field.Expr) IGlobalsDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g globalsDo) Join(table schema.Tabler, on ...field.Expr) IGlobalsDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g globalsDo) LeftJoin(table schema.Tabler, on ...field.Expr) IGlobalsDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g globalsDo) RightJoin(table schema.Tabler, on ...field.Expr) IGlobalsDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g globalsDo) Group(cols ...field.Expr) IGlobalsDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g globalsDo) Having(conds ...gen.Condition) IGlobalsDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g globalsDo) Limit(limit int) IGlobalsDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g globalsDo) Offset(offset int) IGlobalsDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g globalsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IGlobalsDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g globalsDo) Unscoped() IGlobalsDo {
	return g.withDO(g.DO.Unscoped())
}

func (g globalsDo) Create(values ...*models.Globals) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g globalsDo) CreateInBatches(values []*models.Globals, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g globalsDo) Save(values ...*models.Globals) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g globalsDo) First() (*models.Globals, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Globals), nil
	}
}

func (g globalsDo) Take() (*models.Globals, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Globals), nil
	}
}

func (g globalsDo) Last() (*models.Globals, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Globals), nil
	}
}

func (g globalsDo) Find() ([]*models.Globals, error) {
	result, err := g.DO.Find()
	return result.([]*models.Globals), err
}

func (g globalsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Globals, err error) {
	buf := make([]*models.Globals, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g globalsDo) FindInBatches(result *[]*models.Globals, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g globalsDo) Attrs(attrs ...field.AssignExpr) IGlobalsDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g globalsDo) Assign(attrs ...field.AssignExpr) IGlobalsDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g globalsDo) Joins(fields ...field.RelationField) IGlobalsDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g globalsDo) Preload(fields ...field.RelationField) IGlobalsDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g globalsDo) FirstOrInit() (*models.Globals, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Globals), nil
	}
}

func (g globalsDo) FirstOrCreate() (*models.Globals, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Globals), nil
	}
}

func (g globalsDo) FindByPage(offset int, limit int) (result []*models.Globals, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g globalsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g globalsDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g globalsDo) Delete(models ...*models.Globals) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *globalsDo) withDO(do gen.Dao) *globalsDo {
	g.DO = *do.(*gen.DO)
	return g
}
