// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"dealscanner/internal/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newGumtree(db *gorm.DB, opts ...gen.DOOption) gumtree {
	_gumtree := gumtree{}

	_gumtree.gumtreeDo.UseDB(db, opts...)
	_gumtree.gumtreeDo.UseModel(&models.Gumtree{})

	tableName := _gumtree.gumtreeDo.TableName()
	_gumtree.ALL = field.NewAsterisk(tableName)
	_gumtree.Url = field.NewString(tableName, "url")
	_gumtree.MaxPrice = field.NewFloat64(tableName, "maxPrice")
	_gumtree.QueryId = field.NewString(tableName, "queryId")
	_gumtree.Query = gumtreeBelongsToQuery{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Query", "models.SearchQuery"),
	}

	_gumtree.fillFieldMap()

	return _gumtree
}

type gumtree struct {
	gumtreeDo gumtreeDo

	ALL      field.Asterisk
	Url      field.String
	MaxPrice field.Float64
	QueryId  field.String
	Query    gumtreeBelongsToQuery

	fieldMap map[string]field.Expr
}

func (g gumtree) Table(newTableName string) *gumtree {
	g.gumtreeDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g gumtree) As(alias string) *gumtree {
	g.gumtreeDo.DO = *(g.gumtreeDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *gumtree) updateTableName(table string) *gumtree {
	g.ALL = field.NewAsterisk(table)
	g.Url = field.NewString(table, "url")
	g.MaxPrice = field.NewFloat64(table, "maxPrice")
	g.QueryId = field.NewString(table, "queryId")

	g.fillFieldMap()

	return g
}

func (g *gumtree) WithContext(ctx context.Context) IGumtreeDo { return g.gumtreeDo.WithContext(ctx) }

func (g gumtree) TableName() string { return g.gumtreeDo.TableName() }

func (g gumtree) Alias() string { return g.gumtreeDo.Alias() }

func (g gumtree) Columns(cols ...field.Expr) gen.Columns { return g.gumtreeDo.Columns(cols...) }

func (g *gumtree) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *gumtree) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 4)
	g.fieldMap["url"] = g.Url
	g.fieldMap["maxPrice"] = g.MaxPrice
	g.fieldMap["queryId"] = g.QueryId

}

func (g gumtree) clone(db *gorm.DB) gumtree {
	g.gumtreeDo.ReplaceConnPool(db.Statement.ConnPool)
	g.Query.db = db.Session(&gorm.Session{Initialized: true})
	g.Query.db.Statement.ConnPool = db.Statement.ConnPool
	return g
}

func (g gumtree) replaceDB(db *gorm.DB) gumtree {
	g.gumtreeDo.ReplaceDB(db)
	g.Query.db = db.Session(&gorm.Session{})
	return g
}

type gumtreeBelongsToQuery struct {
	db *gorm.DB

	field.RelationField
}

func (a gumtreeBelongsToQuery) Where(conds ...field.Expr) *gumtreeBelongsToQuery {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a gumtreeBelongsToQuery) WithContext(ctx context.Context) *gumtreeBelongsToQuery {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a gumtreeBelongsToQuery) Session(session *gorm.Session) *gumtreeBelongsToQuery {
	a.db = a.db.Session(session)
	return &a
}

func (a gumtreeBelongsToQuery) Model(m *models.Gumtree) *gumtreeBelongsToQueryTx {
	return &gumtreeBelongsToQueryTx{a.db.Model(m).Association(a.Name())}
}

func (a gumtreeBelongsToQuery) Unscoped() *gumtreeBelongsToQuery {
	a.db = a.db.Unscoped()
	return &a
}

type gumtreeBelongsToQueryTx struct{ tx *gorm.Association }

func (a gumtreeBelongsToQueryTx) Find() (result *models.SearchQuery, err error) {
	return result, a.tx.Find(&result)
}

func (a gumtreeBelongsToQueryTx) Append(values ...*models.SearchQuery) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a gumtreeBelongsToQueryTx) Replace(values ...*models.SearchQuery) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a gumtreeBelongsToQueryTx) Delete(values ...*models.SearchQuery) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a gumtreeBelongsToQueryTx) Clear() error {
	return a.tx.Clear()
}

func (a gumtreeBelongsToQueryTx) Count() int64 {
	return a.tx.Count()
}

func (a gumtreeBelongsToQueryTx) Unscoped() *gumtreeBelongsToQueryTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type gumtreeDo struct{ gen.DO }

type IGumtreeDo interface {
	gen.SubQuery
	Debug() IGumtreeDo
	WithContext(ctx context.Context) IGumtreeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IGumtreeDo
	WriteDB() IGumtreeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IGumtreeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IGumtreeDo
	Not(conds ...gen.Condition) IGumtreeDo
	Or(conds ...gen.Condition) IGumtreeDo
	Select(conds ...field.Expr) IGumtreeDo
	Where(conds ...gen.Condition) IGumtreeDo
	Order(conds ...field.Expr) IGumtreeDo
	Distinct(cols ...field.Expr) IGumtreeDo
	Omit(cols ...field.Expr) IGumtreeDo
	Join(table schema.Tabler, on ...field.Expr) IGumtreeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IGumtreeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IGumtreeDo
	Group(cols ...field.Expr) IGumtreeDo
	Having(conds ...gen.Condition) IGumtreeDo
	Limit(limit int) IGumtreeDo
	Offset(offset int) IGumtreeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IGumtreeDo
	Unscoped() IGumtreeDo
	Create(values ...*models.Gumtree) error
	CreateInBatches(values []*models.Gumtree, batchSize int) error
	Save(values ...*models.Gumtree) error
	First() (*models.Gumtree, error)
	Take() (*models.Gumtree, error)
	Last() (*models.Gumtree, error)
	Find() ([]*models.Gumtree, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Gumtree, err error)
	FindInBatches(result *[]*models.Gumtree, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Gumtree) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IGumtreeDo
	Assign(attrs ...field.AssignExpr) IGumtreeDo
	Joins(fields ...field.RelationField) IGumtreeDo
	Preload(fields ...field.RelationField) IGumtreeDo
	FirstOrInit() (*models.Gumtree, error)
	FirstOrCreate() (*models.Gumtree, error)
	FindByPage(offset int, limit int) (result []*models.Gumtree, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IGumtreeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (g gumtreeDo) Debug() IGumtreeDo {
	return g.withDO(g.DO.Debug())
}

func (g gumtreeDo) WithContext(ctx context.Context) IGumtreeDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g gumtreeDo) ReadDB() IGumtreeDo {
	return g.Clauses(dbresolver.Read)
}

func (g gumtreeDo) WriteDB() IGumtreeDo {
	return g.Clauses(dbresolver.Write)
}

func (g gumtreeDo) Session(config *gorm.Session) IGumtreeDo {
	return g.withDO(g.DO.Session(config))
}

func (g gumtreeDo) Clauses(conds ...clause.Expression) IGumtreeDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g gumtreeDo) Returning(value interface{}, columns ...string) IGumtreeDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g gumtreeDo) Not(conds ...gen.Condition) IGumtreeDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g gumtreeDo) Or(conds ...gen.Condition) IGumtreeDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g gumtreeDo) Select(conds ...field.Expr) IGumtreeDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g gumtreeDo) Where(conds ...gen.Condition) IGumtreeDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g gumtreeDo) Order(conds ...field.Expr) IGumtreeDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g gumtreeDo) Distinct(cols ...field.Expr) IGumtreeDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g gumtreeDo) Omit(cols ...field.Expr) IGumtreeDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g gumtreeDo) Join(table schema.Tabler, on ...field.Expr) IGumtreeDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g gumtreeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IGumtreeDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g gumtreeDo) RightJoin(table schema.Tabler, on ...field.Expr) IGumtreeDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g gumtreeDo) Group(cols ...field.Expr) IGumtreeDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g gumtreeDo) Having(conds ...gen.Condition) IGumtreeDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g gumtreeDo) Limit(limit int) IGumtreeDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g gumtreeDo) Offset(offset int) IGumtreeDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g gumtreeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IGumtreeDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g gumtreeDo) Unscoped() IGumtreeDo {
	return g.withDO(g.DO.Unscoped())
}

func (g gumtreeDo) Create(values ...*models.Gumtree) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g gumtreeDo) CreateInBatches(values []*models.Gumtree, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g gumtreeDo) Save(values ...*models.Gumtree) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g gumtreeDo) First() (*models.Gumtree, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Gumtree), nil
	}
}

func (g gumtreeDo) Take() (*models.Gumtree, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Gumtree), nil
	}
}

func (g gumtreeDo) Last() (*models.Gumtree, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Gumtree), nil
	}
}

func (g gumtreeDo) Find() ([]*models.Gumtree, error) {
	result, err := g.DO.Find()
	return result.([]*models.Gumtree), err
}

func (g gumtreeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Gumtree, err error) {
	buf := make([]*models.Gumtree, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g gumtreeDo) FindInBatches(result *[]*models.Gumtree, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g gumtreeDo) Attrs(attrs ...field.AssignExpr) IGumtreeDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g gumtreeDo) Assign(attrs ...field.AssignExpr) IGumtreeDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g gumtreeDo) Joins(fields ...field.RelationField) IGumtreeDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g gumtreeDo) Preload(fields ...field.RelationField) IGumtreeDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g gumtreeDo) FirstOrInit() (*models.Gumtree, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Gumtree), nil
	}
}

func (g gumtreeDo) FirstOrCreate() (*models.Gumtree, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Gumtree), nil
	}
}

func (g gumtreeDo) FindByPage(offset int, limit int) (result []*models.Gumtree, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g gumtreeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g gumtreeDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g gumtreeDo) Delete(models ...*models.Gumtree) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *gumtreeDo) withDO(do gen.Dao) *gumtreeDo {
	g.DO = *do.(*gen.DO)
	return g
}
