// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"dealscanner/internal/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newListingObservation(db *gorm.DB, opts ...gen.DOOption) listingObservation {
	_listingObservation := listingObservation{}

	_listingObservation.listingObservationDo.UseDB(db, opts...)
	_listingObservation.listingObservationDo.UseModel(&models.ListingObservation{})

	tableName := _listingObservation.listingObservationDo.TableName()
	_listingObservation.ALL = field.NewAsterisk(tableName)
	_listingObservation.ID = field.NewString(tableName, "id")
	_listingObservation.ListingId = field.NewString(tableName, "listingId")
	_listingObservation.Source = field.NewString(tableName, "source")
	_listingObservation.ObservedAt = field.NewTime(tableName, "observedAt")
	_listingObservation.Price = field.NewFloat64(tableName, "price")
	_listingObservation.Shipping = field.NewFloat64(tableName, "shipping")
	_listingObservation.TotalPrice = field.NewFloat64(tableName, "totalPrice")
	_listingObservation.Currency = field.NewString(tableName, "currency")
	_listingObservation.Title = field.NewString(tableName, "title")
	_listingObservation.ImageUrl = field.NewString(tableName, "imageUrl")
	_listingObservation.Description = field.NewString(tableName, "description")
	_listingObservation.Availability = field.NewString(tableName, "availability")

	_listingObservation.fillFieldMap()

	return _listingObservation
}

type listingObservation struct {
	listingObservationDo listingObservationDo

	ALL          field.Asterisk
	ID           field.String
	ListingId    field.String
	Source       field.String
	ObservedAt   field.Time
	Price        field.Float64
	Shipping     field.Float64
	TotalPrice   field.Float64
	Currency     field.String
	Title        field.String
	ImageUrl     field.String
	Description  field.String
	Availability field.String

	fieldMap map[string]field.Expr
}

func (l listingObservation) Table(newTableName string) *listingObservation {
	l.listingObservationDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l listingObservation) As(alias string) *listingObservation {
	l.listingObservationDo.DO = *(l.listingObservationDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *listingObservation) updateTableName(table string) *listingObservation {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewString(table, "id")
	l.ListingId = field.NewString(table, "listingId")
	l.Source = field.NewString(table, "source")
	l.ObservedAt = field.NewTime(table, "observedAt")
	l.Price = field.NewFloat64(table, "price")
	l.Shipping = field.NewFloat64(table, "shipping")
	l.TotalPrice = field.NewFloat64(table, "totalPrice")
	l.Currency = field.NewString(table, "currency")
	l.Title = field.NewString(table, "title")
	l.ImageUrl = field.NewString(table, "imageUrl")
	l.Description = field.NewString(table, "description")
	l.Availability = field.NewString(table, "availability")

	l.fillFieldMap()

	return l
}

func (l *listingObservation) WithContext(ctx context.Context) IListingObservationDo {
	return l.listingObservationDo.WithContext(ctx)
}

func (l listingObservation) TableName() string { return l.listingObservationDo.TableName() }

func (l listingObservation) Alias() string { return l.listingObservationDo.Alias() }

func (l listingObservation) Columns(cols ...field.Expr) gen.Columns {
	return l.listingObservationDo.Columns(cols...)
}

func (l *listingObservation) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *listingObservation) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 12)
	l.fieldMap["id"] = l.ID
	l.fieldMap["listingId"] = l.ListingId
	l.fieldMap["source"] = l.Source
	l.fieldMap["observedAt"] = l.ObservedAt
	l.fieldMap["price"] = l.Price
	l.fieldMap["shipping"] = l.Shipping
	l.fieldMap["totalPrice"] = l.TotalPrice
	l.fieldMap["currency"] = l.Currency
	l.fieldMap["title"] = l.Title
	l.fieldMap["imageUrl"] = l.ImageUrl
	l.fieldMap["description"] = l.Description
	l.fieldMap["availability"] = l.Availability
}

func (l listingObservation) clone(db *gorm.DB) listingObservation {
	l.listingObservationDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l listingObservation) replaceDB(db *gorm.DB) listingObservation {
	l.listingObservationDo.ReplaceDB(db)
	return l
}

type listingObservationDo struct{ gen.DO }

type IListingObservationDo interface {
	gen.SubQuery
	Debug() IListingObservationDo
	WithContext(ctx context.Context) IListingObservationDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IListingObservationDo
	WriteDB() IListingObservationDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IListingObservationDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IListingObservationDo
	Not(conds ...gen.Condition) IListingObservationDo
	Or(conds ...gen.Condition) IListingObservationDo
	Select(conds ...field.Expr) IListingObservationDo
	Where(conds ...gen.Condition) IListingObservationDo
	Order(conds ...field.Expr) IListingObservationDo
	Distinct(cols ...field.Expr) IListingObservationDo
	Omit(cols ...field.Expr) IListingObservationDo
	Join(table schema.Tabler, on ...field.Expr) IListingObservationDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IListingObservationDo
	RightJoin(table schema.Tabler, on ...field.Expr) IListingObservationDo
	Group(cols ...field.Expr) IListingObservationDo
	Having(conds ...gen.Condition) IListingObservationDo
	Limit(limit int) IListingObservationDo
	Offset(offset int) IListingObservationDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IListingObservationDo
	Unscoped() IListingObservationDo
	Create(values ...*models.ListingObservation) error
	CreateInBatches(values []*models.ListingObservation, batchSize int) error
	Save(values ...*models.ListingObservation) error
	First() (*models.ListingObservation, error)
	Take() (*models.ListingObservation, error)
	Last() (*models.ListingObservation, error)
	Find() ([]*models.ListingObservation, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ListingObservation, err error)
	FindInBatches(result *[]*models.ListingObservation, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.ListingObservation) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IListingObservationDo
	Assign(attrs ...field.AssignExpr) IListingObservationDo
	Joins(fields ...field.RelationField) IListingObservationDo
	Preload(fields ...field.RelationField) IListingObservationDo
	FirstOrInit() (*models.ListingObservation, error)
	FirstOrCreate() (*models.ListingObservation, error)
	FindByPage(offset int, limit int) (result []*models.ListingObservation, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IListingObservationDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (l listingObservationDo) Debug() IListingObservationDo {
	return l.withDO(l.DO.Debug())
}

func (l listingObservationDo) WithContext(ctx context.Context) IListingObservationDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l listingObservationDo) ReadDB() IListingObservationDo {
	return l.Clauses(dbresolver.Read)
}

func (l listingObservationDo) WriteDB() IListingObservationDo {
	return l.Clauses(dbresolver.Write)
}

func (l listingObservationDo) Session(config *gorm.Session) IListingObservationDo {
	return l.withDO(l.DO.Session(config))
}

func (l listingObservationDo) Clauses(conds ...clause.Expression) IListingObservationDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l listingObservationDo) Returning(value interface{}, columns ...string) IListingObservationDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l listingObservationDo) Not(conds ...gen.Condition) IListingObservationDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l listingObservationDo) Or(conds ...gen.Condition) IListingObservationDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l listingObservationDo) Select(conds ...field.Expr) IListingObservationDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l listingObservationDo) Where(conds ...gen.Condition) IListingObservationDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l listingObservationDo) Order(conds ...field.Expr) IListingObservationDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l listingObservationDo) Distinct(cols ...field.Expr) IListingObservationDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l listingObservationDo) Omit(cols ...field.Expr) IListingObservationDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l listingObservationDo) Join(table schema.Tabler, on ...field.Expr) IListingObservationDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l listingObservationDo) LeftJoin(table schema.Tabler, on ...field.Expr) IListingObservationDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l listingObservationDo) RightJoin(table schema.Tabler, on ...field.Expr) IListingObservationDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l listingObservationDo) Group(cols ...field.Expr) IListingObservationDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l listingObservationDo) Having(conds ...gen.Condition) IListingObservationDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l listingObservationDo) Limit(limit int) IListingObservationDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l listingObservationDo) Offset(offset int) IListingObservationDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l listingObservationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IListingObservationDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l listingObservationDo) Unscoped() IListingObservationDo {
	return l.withDO(l.DO.Unscoped())
}

func (l listingObservationDo) Create(values ...*models.ListingObservation) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l listingObservationDo) CreateInBatches(values []*models.ListingObservation, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l listingObservationDo) Save(values ...*models.ListingObservation) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l listingObservationDo) First() (*models.ListingObservation, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.ListingObservation), nil
	}
}

func (l listingObservationDo) Take() (*models.ListingObservation, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.ListingObservation), nil
	}
}

func (l listingObservationDo) Last() (*models.ListingObservation, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.ListingObservation), nil
	}
}

func (l listingObservationDo) Find() ([]*models.ListingObservation, error) {
	result, err := l.DO.Find()
	return result.([]*models.ListingObservation), err
}

func (l listingObservationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ListingObservation, err error) {
	buf := make([]*models.ListingObservation, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l listingObservationDo) FindInBatches(result *[]*models.ListingObservation, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l listingObservationDo) Attrs(attrs ...field.AssignExpr) IListingObservationDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l listingObservationDo) Assign(attrs ...field.AssignExpr) IListingObservationDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l listingObservationDo) Joins(fields ...field.RelationField) IListingObservationDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l listingObservationDo) Preload(fields ...field.RelationField) IListingObservationDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l listingObservationDo) FirstOrInit() (*models.ListingObservation, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.ListingObservation), nil
	}
}

func (l listingObservationDo) FirstOrCreate() (*models.ListingObservation, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.ListingObservation), nil
	}
}

func (l listingObservationDo) FindByPage(offset int, limit int) (result []*models.ListingObservation, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l listingObservationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l listingObservationDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l listingObservationDo) Delete(models ...*models.ListingObservation) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *listingObservationDo) withDO(do gen.Dao) *listingObservationDo {
	l.DO = *do.(*gen.DO)
	return l
}
