// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"dealscanner/internal/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newListing(db *gorm.DB, opts ...gen.DOOption) listing {
	_listing := listing{}

	_listing.listingDo.UseDB(db, opts...)
	_listing.listingDo.UseModel(&models.Listing{})

	tableName := _listing.listingDo.TableName()
	_listing.ALL = field.NewAsterisk(tableName)
	_listing.ID = field.NewString(tableName, "id")
	_listing.Source = field.NewString(tableName, "source")
	_listing.ExternalId = field.NewString(tableName, "externalId")
	_listing.CanonicalUrl = field.NewString(tableName, "canonicalUrl")
	_listing.Title = field.NewString(tableName, "title")
	_listing.ImageUrl = field.NewString(tableName, "imageUrl")
	_listing.Description = field.NewString(tableName, "description")
	_listing.Availability = field.NewString(tableName, "availability")
	_listing.FirstSeenAt = field.NewTime(tableName, "firstSeenAt")
	_listing.LastSeenAt = field.NewTime(tableName, "lastSeenAt")
	_listing.LastDetailAt = field.NewTime(tableName, "lastDetailAt")
	_listing.UnavailableAt = field.NewTime(tableName, "unavailableAt")

	_listing.fillFieldMap()

	return _listing
}

type listing struct {
	listingDo listingDo

	ALL           field.Asterisk
	ID            field.String
	Source        field.String
	ExternalId    field.String
	CanonicalUrl  field.String
	Title         field.String
	ImageUrl      field.String
	Description   field.String
	Availability  field.String
	FirstSeenAt   field.Time
	LastSeenAt    field.Time
	LastDetailAt  field.Time
	UnavailableAt field.Time

	fieldMap map[string]field.Expr
}

func (l listing) Table(newTableName string) *listing {
	l.listingDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l listing) As(alias string) *listing {
	l.listingDo.DO = *(l.listingDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *listing) updateTableName(table string) *listing {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewString(table, "id")
	l.Source = field.NewString(table, "source")
	l.ExternalId = field.NewString(table, "externalId")
	l.CanonicalUrl = field.NewString(table, "canonicalUrl")
	l.Title = field.NewString(table, "title")
	l.ImageUrl = field.NewString(table, "imageUrl")
	l.Description = field.NewString(table, "description")
	l.Availability = field.NewString(table, "availability")
	l.FirstSeenAt = field.NewTime(table, "firstSeenAt")
	l.LastSeenAt = field.NewTime(table, "lastSeenAt")
	l.LastDetailAt = field.NewTime(table, "lastDetailAt")
	l.UnavailableAt = field.NewTime(table, "unavailableAt")

	l.fillFieldMap()

	return l
}

func (l *listing) WithContext(ctx context.Context) IListingDo { return l.listingDo.WithContext(ctx) }

func (l listing) TableName() string { return l.listingDo.TableName() }

func (l listing) Alias() string { return l.listingDo.Alias() }

func (l listing) Columns(cols ...field.Expr) gen.Columns { return l.listingDo.Columns(cols...) }

func (l *listing) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *listing) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 12)
	l.fieldMap["id"] = l.ID
	l.fieldMap["source"] = l.Source
	l.fieldMap["externalId"] = l.ExternalId
	l.fieldMap["canonicalUrl"] = l.CanonicalUrl
	l.fieldMap["title"] = l.Title
	l.fieldMap["imageUrl"] = l.ImageUrl
	l.fieldMap["description"] = l.Description
	l.fieldMap["availability"] = l.Availability
	l.fieldMap["firstSeenAt"] = l.FirstSeenAt
	l.fieldMap["lastSeenAt"] = l.LastSeenAt
	l.fieldMap["lastDetailAt"] = l.LastDetailAt
	l.fieldMap["unavailableAt"] = l.UnavailableAt
}

func (l listing) clone(db *gorm.DB) listing {
	l.listingDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l listing) replaceDB(db *gorm.DB) listing {
	l.listingDo.ReplaceDB(db)
	return l
}

type listingDo struct{ gen.DO }

type IListingDo interface {
	gen.SubQuery
	Debug() IListingDo
	WithContext(ctx context.Context) IListingDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IListingDo
	WriteDB() IListingDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IListingDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IListingDo
	Not(conds ...gen.Condition) IListingDo
	Or(conds ...gen.Condition) IListingDo
	Select(conds ...field.Expr) IListingDo
	Where(conds ...gen.Condition) IListingDo
	Order(conds ...field.Expr) IListingDo
	Distinct(cols ...field.Expr) IListingDo
	Omit(cols ...field.Expr) IListingDo
	Join(table schema.Tabler, on ...field.Expr) IListingDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IListingDo
	RightJoin(table schema.Tabler, on ...field.Expr) IListingDo
	Group(cols ...field.Expr) IListingDo
	Having(conds ...gen.Condition) IListingDo
	Limit(limit int) IListingDo
	Offset(offset int) IListingDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IListingDo
	Unscoped() IListingDo
	Create(values ...*models.Listing) error
	CreateInBatches(values []*models.Listing, batchSize int) error
	Save(values ...*models.Listing) error
	First() (*models.Listing, error)
	Take() (*models.Listing, error)
	Last() (*models.Listing, error)
	Find() ([]*models.Listing, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Listing, err error)
	FindInBatches(result *[]*models.Listing, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Listing) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IListingDo
	Assign(attrs ...field.AssignExpr) IListingDo
	Joins(fields ...field.RelationField) IListingDo
	Preload(fields ...field.RelationField) IListingDo
	FirstOrInit() (*models.Listing, error)
	FirstOrCreate() (*models.Listing, error)
	FindByPage(offset int, limit int) (result []*models.Listing, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IListingDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (l listingDo) Debug() IListingDo {
	return l.withDO(l.DO.Debug())
}

func (l listingDo) WithContext(ctx context.Context) IListingDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l listingDo) ReadDB() IListingDo {
	return l.Clauses(dbresolver.Read)
}

func (l listingDo) WriteDB() IListingDo {
	return l.Clauses(dbresolver.Write)
}

func (l listingDo) Session(config *gorm.Session) IListingDo {
	return l.withDO(l.DO.Session(config))
}

func (l listingDo) Clauses(conds ...clause.Expression) IListingDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l listingDo) Returning(value interface{}, columns ...string) IListingDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l listingDo) Not(conds ...gen.Condition) IListingDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l listingDo) Or(conds ...gen.Condition) IListingDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l listingDo) Select(conds ...field.Expr) IListingDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l listingDo) Where(conds ...gen.Condition) IListingDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l listingDo) Order(conds ...field.Expr) IListingDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l listingDo) Distinct(cols ...field.Expr) IListingDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l listingDo) Omit(cols ...field.Expr) IListingDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l listingDo) Join(table schema.Tabler, on ...field.Expr) IListingDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l listingDo) LeftJoin(table schema.Tabler, on ...field.Expr) IListingDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l listingDo) RightJoin(table schema.Tabler, on ...field.Expr) IListingDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l listingDo) Group(cols ...field.Expr) IListingDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l listingDo) Having(conds ...gen.Condition) IListingDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l listingDo) Limit(limit int) IListingDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l listingDo) Offset(offset int) IListingDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l listingDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IListingDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l listingDo) Unscoped() IListingDo {
	return l.withDO(l.DO.Unscoped())
}

func (l listingDo) Create(values ...*models.Listing) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l listingDo) CreateInBatches(values []*models.Listing, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l listingDo) Save(values ...*models.Listing) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l listingDo) First() (*models.Listing, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Listing), nil
	}
}

func (l listingDo) Take() (*models.Listing, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Listing), nil
	}
}

func (l listingDo) Last() (*models.Listing, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Listing), nil
	}
}

func (l listingDo) Find() ([]*models.Listing, error) {
	result, err := l.DO.Find()
	return result.([]*models.Listing), err
}

func (l listingDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Listing, err error) {
	buf := make([]*models.Listing, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l listingDo) FindInBatches(result *[]*models.Listing, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l listingDo) Attrs(attrs ...field.AssignExpr) IListingDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l listingDo) Assign(attrs ...field.AssignExpr) IListingDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l listingDo) Joins(fields ...field.RelationField) IListingDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l listingDo) Preload(fields ...field.RelationField) IListingDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l listingDo) FirstOrInit() (*models.Listing, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Listing), nil
	}
}

func (l listingDo) FirstOrCreate() (*models.Listing, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Listing), nil
	}
}

func (l listingDo) FindByPage(offset int, limit int) (result []*models.Listing, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l listingDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l listingDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l listingDo) Delete(models ...*models.Listing) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *listingDo) withDO(do gen.Dao) *listingDo {
	l.DO = *do.(*gen.DO)
	return l
}
