// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"dealscanner/internal/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newSearchQuery(db *gorm.DB, opts ...gen.DOOption) searchQuery {
	_searchQuery := searchQuery{}

	_searchQuery.searchQueryDo.UseDB(db, opts...)
	_searchQuery.searchQueryDo.UseModel(&models.SearchQuery{})

	tableName := _searchQuery.searchQueryDo.TableName()
	_searchQuery.ALL = field.NewAsterisk(tableName)
	_searchQuery.ID = field.NewString(tableName, "id")
	_searchQuery.DmOnly = field.NewBool(tableName, "dmOnly")
	_searchQuery.CreatedAt = field.NewTime(tableName, "createdAt")

	_searchQuery.fillFieldMap()

	return _searchQuery
}

type searchQuery struct {
	searchQueryDo searchQueryDo

	ALL       field.Asterisk
	ID        field.String
	DmOnly    field.Bool
	CreatedAt field.Time

	fieldMap map[string]field.Expr
}

func (s searchQuery) Table(newTableName string) *searchQuery {
	s.searchQueryDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s searchQuery) As(alias string) *searchQuery {
	s.searchQueryDo.DO = *(s.searchQueryDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *searchQuery) updateTableName(table string) *searchQuery {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewString(table, "id")
	s.DmOnly = field.NewBool(table, "dmOnly")
	s.CreatedAt = field.NewTime(table, "createdAt")

	s.fillFieldMap()

	return s
}

func (s *searchQuery) WithContext(ctx context.Context) ISearchQueryDo {
	return s.searchQueryDo.WithContext(ctx)
}

func (s searchQuery) TableName() string { return s.searchQueryDo.TableName() }

func (s searchQuery) Alias() string { return s.searchQueryDo.Alias() }

func (s searchQuery) Columns(cols ...field.Expr) gen.Columns { return s.searchQueryDo.Columns(cols...) }

func (s *searchQuery) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *searchQuery) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 3)
	s.fieldMap["id"] = s.ID
	s.fieldMap["dmOnly"] = s.DmOnly
	s.fieldMap["createdAt"] = s.CreatedAt
}

func (s searchQuery) clone(db *gorm.DB) searchQuery {
	s.searchQueryDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s searchQuery) replaceDB(db *gorm.DB) searchQuery {
	s.searchQueryDo.ReplaceDB(db)
	return s
}

type searchQueryDo struct{ gen.DO }

type ISearchQueryDo interface {
	gen.SubQuery
	Debug() ISearchQueryDo
	WithContext(ctx context.Context) ISearchQueryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISearchQueryDo
	WriteDB() ISearchQueryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISearchQueryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISearchQueryDo
	Not(conds ...gen.Condition) ISearchQueryDo
	Or(conds ...gen.Condition) ISearchQueryDo
	Select(conds ...field.Expr) ISearchQueryDo
	Where(conds ...gen.Condition) ISearchQueryDo
	Order(conds ...field.Expr) ISearchQueryDo
	Distinct(cols ...field.Expr) ISearchQueryDo
	Omit(cols ...field.Expr) ISearchQueryDo
	Join(table schema.Tabler, on ...field.Expr) ISearchQueryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISearchQueryDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISearchQueryDo
	Group(cols ...field.Expr) ISearchQueryDo
	Having(conds ...gen.Condition) ISearchQueryDo
	Limit(limit int) ISearchQueryDo
	Offset(offset int) ISearchQueryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISearchQueryDo
	Unscoped() ISearchQueryDo
	Create(values ...*models.SearchQuery) error
	CreateInBatches(values []*models.SearchQuery, batchSize int) error
	Save(values ...*models.SearchQuery) error
	First() (*models.SearchQuery, error)
	Take() (*models.SearchQuery, error)
	Last() (*models.SearchQuery, error)
	Find() ([]*models.SearchQuery, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SearchQuery, err error)
	FindInBatches(result *[]*models.SearchQuery, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.SearchQuery) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISearchQueryDo
	Assign(attrs ...field.AssignExpr) ISearchQueryDo
	Joins(fields ...field.RelationField) ISearchQueryDo
	Preload(fields ...field.RelationField) ISearchQueryDo
	FirstOrInit() (*models.SearchQuery, error)
	FirstOrCreate() (*models.SearchQuery, error)
	FindByPage(offset int, limit int) (result []*models.SearchQuery, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISearchQueryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s searchQueryDo) Debug() ISearchQueryDo {
	return s.withDO(s.DO.Debug())
}

func (s searchQueryDo) WithContext(ctx context.Context) ISearchQueryDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s searchQueryDo) ReadDB() ISearchQueryDo {
	return s.Clauses(dbresolver.Read)
}

func (s searchQueryDo) WriteDB() ISearchQueryDo {
	return s.Clauses(dbresolver.Write)
}

func (s searchQueryDo) Session(config *gorm.Session) ISearchQueryDo {
	return s.withDO(s.DO.Session(config))
}

func (s searchQueryDo) Clauses(conds ...clause.Expression) ISearchQueryDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s searchQueryDo) Returning(value interface{}, columns ...string) ISearchQueryDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s searchQueryDo) Not(conds ...gen.Condition) ISearchQueryDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s searchQueryDo) Or(conds ...gen.Condition) ISearchQueryDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s searchQueryDo) Select(conds ...field.Expr) ISearchQueryDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s searchQueryDo) Where(conds ...gen.Condition) ISearchQueryDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s searchQueryDo) Order(conds ...field.Expr) ISearchQueryDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s searchQueryDo) Distinct(cols ...field.Expr) ISearchQueryDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s searchQueryDo) Omit(cols ...field.Expr) ISearchQueryDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s searchQueryDo) Join(table schema.Tabler, on ...field.Expr) ISearchQueryDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s searchQueryDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISearchQueryDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s searchQueryDo) RightJoin(table schema.Tabler, on ...field.Expr) ISearchQueryDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s searchQueryDo) Group(cols ...field.Expr) ISearchQueryDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s searchQueryDo) Having(conds ...gen.Condition) ISearchQueryDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s searchQueryDo) Limit(limit int) ISearchQueryDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s searchQueryDo) Offset(offset int) ISearchQueryDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s searchQueryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISearchQueryDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s searchQueryDo) Unscoped() ISearchQueryDo {
	return s.withDO(s.DO.Unscoped())
}

func (s searchQueryDo) Create(values ...*models.SearchQuery) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s searchQueryDo) CreateInBatches(values []*models.SearchQuery, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s searchQueryDo) Save(values ...*models.SearchQuery) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s searchQueryDo) First() (*models.SearchQuery, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.SearchQuery), nil
	}
}

func (s searchQueryDo) Take() (*models.SearchQuery, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.SearchQuery), nil
	}
}

func (s searchQueryDo) Last() (*models.SearchQuery, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.SearchQuery), nil
	}
}

func (s searchQueryDo) Find() ([]*models.SearchQuery, error) {
	result, err := s.DO.Find()
	return result.([]*models.SearchQuery), err
}

func (s searchQueryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SearchQuery, err error) {
	buf := make([]*models.SearchQuery, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s searchQueryDo) FindInBatches(result *[]*models.SearchQuery, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s searchQueryDo) Attrs(attrs ...field.AssignExpr) ISearchQueryDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s searchQueryDo) Assign(attrs ...field.AssignExpr) ISearchQueryDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s searchQueryDo) Joins(fields ...field.RelationField) ISearchQueryDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s searchQueryDo) Preload(fields ...field.RelationField) ISearchQueryDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s searchQueryDo) FirstOrInit() (*models.SearchQuery, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.SearchQuery), nil
	}
}

func (s searchQueryDo) FirstOrCreate() (*models.SearchQuery, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.SearchQuery), nil
	}
}

func (s searchQueryDo) FindByPage(offset int, limit int) (result []*models.SearchQuery, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s searchQueryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s searchQueryDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s searchQueryDo) Delete(models ...*models.SearchQuery) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *searchQueryDo) withDO(do gen.Dao) *searchQueryDo {
	s.DO = *do.(*gen.DO)
	return s
}
