// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"dealscanner/internal/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newQueryListingState(db *gorm.DB, opts ...gen.DOOption) queryListingState {
	_queryListingState := queryListingState{}

	_queryListingState.queryListingStateDo.UseDB(db, opts...)
	_queryListingState.queryListingStateDo.UseModel(&models.QueryListingState{})

	tableName := _queryListingState.queryListingStateDo.TableName()
	_queryListingState.ALL = field.NewAsterisk(tableName)
	_queryListingState.QueryId = field.NewString(tableName, "queryId")
	_queryListingState.ListingId = field.NewString(tableName, "listingId")
	_queryListingState.Source = field.NewString(tableName, "source")
	_queryListingState.Status = field.NewString(tableName, "status")
	_queryListingState.LastEvaluatedAt = field.NewTime(tableName, "lastEvaluatedAt")
	_queryListingState.FirstMatchedAt = field.NewTime(tableName, "firstMatchedAt")
	_queryListingState.LastMatchedAt = field.NewTime(tableName, "lastMatchedAt")
	_queryListingState.LastRejectedReason = field.NewString(tableName, "lastRejectedReason")
	_queryListingState.LastNotifiedAt = field.NewTime(tableName, "lastNotifiedAt")
	_queryListingState.LastNotifiedTotalPrice = field.NewFloat64(tableName, "lastNotifiedTotalPrice")
	_queryListingState.LowestObservedPrice = field.NewFloat64(tableName, "lowestObservedPrice")
	_queryListingState.Query = queryListingStateBelongsToQuery{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Query", "models.SearchQuery"),
	}

	_queryListingState.Listing = queryListingStateBelongsToListing{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Listing", "models.Listing"),
	}

	_queryListingState.fillFieldMap()

	return _queryListingState
}

type queryListingState struct {
	queryListingStateDo queryListingStateDo

	ALL                    field.Asterisk
	QueryId                field.String
	ListingId              field.String
	Source                 field.String
	Status                 field.String
	LastEvaluatedAt        field.Time
	FirstMatchedAt         field.Time
	LastMatchedAt          field.Time
	LastRejectedReason     field.String
	LastNotifiedAt         field.Time
	LastNotifiedTotalPrice field.Float64
	LowestObservedPrice    field.Float64
	Query                  queryListingStateBelongsToQuery

	Listing queryListingStateBelongsToListing

	fieldMap map[string]field.Expr
}

func (q queryListingState) Table(newTableName string) *queryListingState {
	q.queryListingStateDo.UseTable(newTableName)
	return q.updateTableName(newTableName)
}

func (q queryListingState) As(alias string) *queryListingState {
	q.queryListingStateDo.DO = *(q.queryListingStateDo.As(alias).(*gen.DO))
	return q.updateTableName(alias)
}

func (q *queryListingState) updateTableName(table string) *queryListingState {
	q.ALL = field.NewAsterisk(table)
	q.QueryId = field.NewString(table, "queryId")
	q.ListingId = field.NewString(table, "listingId")
	q.Source = field.NewString(table, "source")
	q.Status = field.NewString(table, "status")
	q.LastEvaluatedAt = field.NewTime(table, "lastEvaluatedAt")
	q.FirstMatchedAt = field.NewTime(table, "firstMatchedAt")
	q.LastMatchedAt = field.NewTime(table, "lastMatchedAt")
	q.LastRejectedReason = field.NewString(table, "lastRejectedReason")
	q.LastNotifiedAt = field.NewTime(table, "lastNotifiedAt")
	q.LastNotifiedTotalPrice = field.NewFloat64(table, "lastNotifiedTotalPrice")
	q.LowestObservedPrice = field.NewFloat64(table, "lowestObservedPrice")

	q.fillFieldMap()

	return q
}

func (q *queryListingState) WithContext(ctx context.Context) IQueryListingStateDo {
	return q.queryListingStateDo.WithContext(ctx)
}

func (q queryListingState) TableName() string { return q.queryListingStateDo.TableName() }

func (q queryListingState) Alias() string { return q.queryListingStateDo.Alias() }

func (q queryListingState) Columns(cols ...field.Expr) gen.Columns {
	return q.queryListingStateDo.Columns(cols...)
}

func (q *queryListingState) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := q.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (q *queryListingState) fillFieldMap() {
	q.fieldMap = make(map[string]field.Expr, 13)
	q.fieldMap["queryId"] = q.QueryId
	q.fieldMap["listingId"] = q.ListingId
	q.fieldMap["source"] = q.Source
	q.fieldMap["status"] = q.Status
	q.fieldMap["lastEvaluatedAt"] = q.LastEvaluatedAt
	q.fieldMap["firstMatchedAt"] = q.FirstMatchedAt
	q.fieldMap["lastMatchedAt"] = q.LastMatchedAt
	q.fieldMap["lastRejectedReason"] = q.LastRejectedReason
	q.fieldMap["lastNotifiedAt"] = q.LastNotifiedAt
	q.fieldMap["lastNotifiedTotalPrice"] = q.LastNotifiedTotalPrice
	q.fieldMap["lowestObservedPrice"] = q.LowestObservedPrice

}

func (q queryListingState) clone(db *gorm.DB) queryListingState {
	q.queryListingStateDo.ReplaceConnPool(db.Statement.ConnPool)
	q.Query.db = db.Session(&gorm.Session{Initialized: true})
	q.Query.db.Statement.ConnPool = db.Statement.ConnPool
	q.Listing.db = db.Session(&gorm.Session{Initialized: true})
	q.Listing.db.Statement.ConnPool = db.Statement.ConnPool
	return q
}

func (q queryListingState) replaceDB(db *gorm.DB) queryListingState {
	q.queryListingStateDo.ReplaceDB(db)
	q.Query.db = db.Session(&gorm.Session{})
	q.Listing.db = db.Session(&gorm.Session{})
	return q
}

type queryListingStateBelongsToQuery struct {
	db *gorm.DB

	field.RelationField
}

func (a queryListingStateBelongsToQuery) Where(conds ...field.Expr) *queryListingStateBelongsToQuery {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a queryListingStateBelongsToQuery) WithContext(ctx context.Context) *queryListingStateBelongsToQuery {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a queryListingStateBelongsToQuery) Session(session *gorm.Session) *queryListingStateBelongsToQuery {
	a.db = a.db.Session(session)
	return &a
}

func (a queryListingStateBelongsToQuery) Model(m *models.QueryListingState) *queryListingStateBelongsToQueryTx {
	return &queryListingStateBelongsToQueryTx{a.db.Model(m).Association(a.Name())}
}

func (a queryListingStateBelongsToQuery) Unscoped() *queryListingStateBelongsToQuery {
	a.db = a.db.Unscoped()
	return &a
}

type queryListingStateBelongsToQueryTx struct{ tx *gorm.Association }

func (a queryListingStateBelongsToQueryTx) Find() (result *models.SearchQuery, err error) {
	return result, a.tx.Find(&result)
}

func (a queryListingStateBelongsToQueryTx) Append(values ...*models.SearchQuery) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a queryListingStateBelongsToQueryTx) Replace(values ...*models.SearchQuery) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a queryListingStateBelongsToQueryTx) Delete(values ...*models.SearchQuery) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a queryListingStateBelongsToQueryTx) Clear() error {
	return a.tx.Clear()
}

func (a queryListingStateBelongsToQueryTx) Count() int64 {
	return a.tx.Count()
}

func (a queryListingStateBelongsToQueryTx) Unscoped() *queryListingStateBelongsToQueryTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type queryListingStateBelongsToListing struct {
	db *gorm.DB

	field.RelationField
}

func (a queryListingStateBelongsToListing) Where(conds ...field.Expr) *queryListingStateBelongsToListing {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a queryListingStateBelongsToListing) WithContext(ctx context.Context) *queryListingStateBelongsToListing {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a queryListingStateBelongsToListing) Session(session *gorm.Session) *queryListingStateBelongsToListing {
	a.db = a.db.Session(session)
	return &a
}

func (a queryListingStateBelongsToListing) Model(m *models.QueryListingState) *queryListingStateBelongsToListingTx {
	return &queryListingStateBelongsToListingTx{a.db.Model(m).Association(a.Name())}
}

func (a queryListingStateBelongsToListing) Unscoped() *queryListingStateBelongsToListing {
	a.db = a.db.Unscoped()
	return &a
}

type queryListingStateBelongsToListingTx struct{ tx *gorm.Association }

func (a queryListingStateBelongsToListingTx) Find() (result *models.Listing, err error) {
	return result, a.tx.Find(&result)
}

func (a queryListingStateBelongsToListingTx) Append(values ...*models.Listing) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a queryListingStateBelongsToListingTx) Replace(values ...*models.Listing) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a queryListingStateBelongsToListingTx) Delete(values ...*models.Listing) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a queryListingStateBelongsToListingTx) Clear() error {
	return a.tx.Clear()
}

func (a queryListingStateBelongsToListingTx) Count() int64 {
	return a.tx.Count()
}

func (a queryListingStateBelongsToListingTx) Unscoped() *queryListingStateBelongsToListingTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type queryListingStateDo struct{ gen.DO }

type IQueryListingStateDo interface {
	gen.SubQuery
	Debug() IQueryListingStateDo
	WithContext(ctx context.Context) IQueryListingStateDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IQueryListingStateDo
	WriteDB() IQueryListingStateDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IQueryListingStateDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IQueryListingStateDo
	Not(conds ...gen.Condition) IQueryListingStateDo
	Or(conds ...gen.Condition) IQueryListingStateDo
	Select(conds ...field.Expr) IQueryListingStateDo
	Where(conds ...gen.Condition) IQueryListingStateDo
	Order(conds ...field.Expr) IQueryListingStateDo
	Distinct(cols ...field.Expr) IQueryListingStateDo
	Omit(cols ...field.Expr) IQueryListingStateDo
	Join(table schema.Tabler, on ...field.Expr) IQueryListingStateDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IQueryListingStateDo
	RightJoin(table schema.Tabler, on ...field.Expr) IQueryListingStateDo
	Group(cols ...field.Expr) IQueryListingStateDo
	Having(conds ...gen.Condition) IQueryListingStateDo
	Limit(limit int) IQueryListingStateDo
	Offset(offset int) IQueryListingStateDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IQueryListingStateDo
	Unscoped() IQueryListingStateDo
	Create(values ...*models.QueryListingState) error
	CreateInBatches(values []*models.QueryListingState, batchSize int) error
	Save(values ...*models.QueryListingState) error
	First() (*models.QueryListingState, error)
	Take() (*models.QueryListingState, error)
	Last() (*models.QueryListingState, error)
	Find() ([]*models.QueryListingState, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.QueryListingState, err error)
	FindInBatches(result *[]*models.QueryListingState, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.QueryListingState) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IQueryListingStateDo
	Assign(attrs ...field.AssignExpr) IQueryListingStateDo
	Joins(fields ...field.RelationField) IQueryListingStateDo
	Preload(fields ...field.RelationField) IQueryListingStateDo
	FirstOrInit() (*models.QueryListingState, error)
	FirstOrCreate() (*models.QueryListingState, error)
	FindByPage(offset int, limit int) (result []*models.QueryListingState, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IQueryListingStateDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (q queryListingStateDo) Debug() IQueryListingStateDo {
	return q.withDO(q.DO.Debug())
}

func (q queryListingStateDo) WithContext(ctx context.Context) IQueryListingStateDo {
	return q.withDO(q.DO.WithContext(ctx))
}

func (q queryListingStateDo) ReadDB() IQueryListingStateDo {
	return q.Clauses(dbresolver.Read)
}

func (q queryListingStateDo) WriteDB() IQueryListingStateDo {
	return q.Clauses(dbresolver.Write)
}

func (q queryListingStateDo) Session(config *gorm.Session) IQueryListingStateDo {
	return q.withDO(q.DO.Session(config))
}

func (q queryListingStateDo) Clauses(conds ...clause.Expression) IQueryListingStateDo {
	return q.withDO(q.DO.Clauses(conds...))
}

func (q queryListingStateDo) Returning(value interface{}, columns ...string) IQueryListingStateDo {
	return q.withDO(q.DO.Returning(value, columns...))
}

func (q queryListingStateDo) Not(conds ...gen.Condition) IQueryListingStateDo {
	return q.withDO(q.DO.Not(conds...))
}

func (q queryListingStateDo) Or(conds ...gen.Condition) IQueryListingStateDo {
	return q.withDO(q.DO.Or(conds...))
}

func (q queryListingStateDo) Select(conds ...field.Expr) IQueryListingStateDo {
	return q.withDO(q.DO.Select(conds...))
}

func (q queryListingStateDo) Where(conds ...gen.Condition) IQueryListingStateDo {
	return q.withDO(q.DO.Where(conds...))
}

func (q queryListingStateDo) Order(conds ...field.Expr) IQueryListingStateDo {
	return q.withDO(q.DO.Order(conds...))
}

func (q queryListingStateDo) Distinct(cols ...field.Expr) IQueryListingStateDo {
	return q.withDO(q.DO.Distinct(cols...))
}

func (q queryListingStateDo) Omit(cols ...field.Expr) IQueryListingStateDo {
	return q.withDO(q.DO.Omit(cols...))
}

func (q queryListingStateDo) Join(table schema.Tabler, on ...field.Expr) IQueryListingStateDo {
	return q.withDO(q.DO.Join(table, on...))
}

func (q queryListingStateDo) LeftJoin(table schema.Tabler, on ...field.Expr) IQueryListingStateDo {
	return q.withDO(q.DO.LeftJoin(table, on...))
}

func (q queryListingStateDo) RightJoin(table schema.Tabler, on ...field.Expr) IQueryListingStateDo {
	return q.withDO(q.DO.RightJoin(table, on...))
}

func (q queryListingStateDo) Group(cols ...field.Expr) IQueryListingStateDo {
	return q.withDO(q.DO.Group(cols...))
}

func (q queryListingStateDo) Having(conds ...gen.Condition) IQueryListingStateDo {
	return q.withDO(q.DO.Having(conds...))
}

func (q queryListingStateDo) Limit(limit int) IQueryListingStateDo {
	return q.withDO(q.DO.Limit(limit))
}

func (q queryListingStateDo) Offset(offset int) IQueryListingStateDo {
	return q.withDO(q.DO.Offset(offset))
}

func (q queryListingStateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IQueryListingStateDo {
	return q.withDO(q.DO.Scopes(funcs...))
}

func (q queryListingStateDo) Unscoped() IQueryListingStateDo {
	return q.withDO(q.DO.Unscoped())
}

func (q queryListingStateDo) Create(values ...*models.QueryListingState) error {
	if len(values) == 0 {
		return nil
	}
	return q.DO.Create(values)
}

func (q queryListingStateDo) CreateInBatches(values []*models.QueryListingState, batchSize int) error {
	return q.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (q queryListingStateDo) Save(values ...*models.QueryListingState) error {
	if len(values) == 0 {
		return nil
	}
	return q.DO.Save(values)
}

func (q queryListingStateDo) First() (*models.QueryListingState, error) {
	if result, err := q.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.QueryListingState), nil
	}
}

func (q queryListingStateDo) Take() (*models.QueryListingState, error) {
	if result, err := q.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.QueryListingState), nil
	}
}

func (q queryListingStateDo) Last() (*models.QueryListingState, error) {
	if result, err := q.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.QueryListingState), nil
	}
}

func (q queryListingStateDo) Find() ([]*models.QueryListingState, error) {
	result, err := q.DO.Find()
	return result.([]*models.QueryListingState), err
}

func (q queryListingStateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.QueryListingState, err error) {
	buf := make([]*models.QueryListingState, 0, batchSize)
	err = q.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (q queryListingStateDo) FindInBatches(result *[]*models.QueryListingState, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return q.DO.FindInBatches(result, batchSize, fc)
}

func (q queryListingStateDo) Attrs(attrs ...field.AssignExpr) IQueryListingStateDo {
	return q.withDO(q.DO.Attrs(attrs...))
}

func (q queryListingStateDo) Assign(attrs ...field.AssignExpr) IQueryListingStateDo {
	return q.withDO(q.DO.Assign(attrs...))
}

func (q queryListingStateDo) Joins(fields ...field.RelationField) IQueryListingStateDo {
	for _, _f := range fields {
		q = *q.withDO(q.DO.Joins(_f))
	}
	return &q
}

func (q queryListingStateDo) Preload(fields ...field.RelationField) IQueryListingStateDo {
	for _, _f := range fields {
		q = *q.withDO(q.DO.Preload(_f))
	}
	return &q
}

func (q queryListingStateDo) FirstOrInit() (*models.QueryListingState, error) {
	if result, err := q.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.QueryListingState), nil
	}
}

func (q queryListingStateDo) FirstOrCreate() (*models.QueryListingState, error) {
	if result, err := q.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.QueryListingState), nil
	}
}

func (q queryListingStateDo) FindByPage(offset int, limit int) (result []*models.QueryListingState, count int64, err error) {
	result, err = q.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = q.Offset(-1).Limit(-1).Count()
	return
}

func (q queryListingStateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = q.Count()
	if err != nil {
		return
	}

	err = q.Offset(offset).Limit(limit).Scan(result)
	return
}

func (q queryListingStateDo) Scan(result interface{}) (err error) {
	return q.DO.Scan(result)
}

func (q queryListingStateDo) Delete(models ...*models.QueryListingState) (result gen.ResultInfo, err error) {
	return q.DO.Delete(models)
}

func (q *queryListingStateDo) withDO(do gen.Dao) *queryListingStateDo {
	q.DO = *do.(*gen.DO)
	return q
}
