// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"dealscanner/internal/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newSalvos(db *gorm.DB, opts ...gen.DOOption) salvos {
	_salvos := salvos{}

	_salvos.salvosDo.UseDB(db, opts...)
	_salvos.salvosDo.UseModel(&models.Salvos{})

	tableName := _salvos.salvosDo.TableName()
	_salvos.ALL = field.NewAsterisk(tableName)
	_salvos.Name = field.NewString(tableName, "name")
	_salvos.MinPrice = field.NewFloat64(tableName, "minPrice")
	_salvos.MaxPrice = field.NewFloat64(tableName, "maxPrice")
	_salvos.QueryId = field.NewString(tableName, "queryId")
	_salvos.Query = salvosBelongsToQuery{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Query", "models.SearchQuery"),
	}

	_salvos.fillFieldMap()

	return _salvos
}

type salvos struct {
	salvosDo salvosDo

	ALL      field.Asterisk
	Name     field.String
	MinPrice field.Float64
	MaxPrice field.Float64
	QueryId  field.String
	Query    salvosBelongsToQuery

	fieldMap map[string]field.Expr
}

func (s salvos) Table(newTableName string) *salvos {
	s.salvosDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s salvos) As(alias string) *salvos {
	s.salvosDo.DO = *(s.salvosDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *salvos) updateTableName(table string) *salvos {
	s.ALL = field.NewAsterisk(table)
	s.Name = field.NewString(table, "name")
	s.MinPrice = field.NewFloat64(table, "minPrice")
	s.MaxPrice = field.NewFloat64(table, "maxPrice")
	s.QueryId = field.NewString(table, "queryId")

	s.fillFieldMap()

	return s
}

func (s *salvos) WithContext(ctx context.Context) ISalvosDo { return s.salvosDo.WithContext(ctx) }

func (s salvos) TableName() string { return s.salvosDo.TableName() }

func (s salvos) Alias() string { return s.salvosDo.Alias() }

func (s salvos) Columns(cols ...field.Expr) gen.Columns { return s.salvosDo.Columns(cols...) }

func (s *salvos) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *salvos) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 5)
	s.fieldMap["name"] = s.Name
	s.fieldMap["minPrice"] = s.MinPrice
	s.fieldMap["maxPrice"] = s.MaxPrice
	s.fieldMap["queryId"] = s.QueryId

}

func (s salvos) clone(db *gorm.DB) salvos {
	s.salvosDo.ReplaceConnPool(db.Statement.ConnPool)
	s.Query.db = db.Session(&gorm.Session{Initialized: true})
	s.Query.db.Statement.ConnPool = db.Statement.ConnPool
	return s
}

func (s salvos) replaceDB(db *gorm.DB) salvos {
	s.salvosDo.ReplaceDB(db)
	s.Query.db = db.Session(&gorm.Session{})
	return s
}

type salvosBelongsToQuery struct {
	db *gorm.DB

	field.RelationField
}

func (a salvosBelongsToQuery) Where(conds ...field.Expr) *salvosBelongsToQuery {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a salvosBelongsToQuery) WithContext(ctx context.Context) *salvosBelongsToQuery {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a salvosBelongsToQuery) Session(session *gorm.Session) *salvosBelongsToQuery {
	a.db = a.db.Session(session)
	return &a
}

func (a salvosBelongsToQuery) Model(m *models.Salvos) *salvosBelongsToQueryTx {
	return &salvosBelongsToQueryTx{a.db.Model(m).Association(a.Name())}
}

func (a salvosBelongsToQuery) Unscoped() *salvosBelongsToQuery {
	a.db = a.db.Unscoped()
	return &a
}

type salvosBelongsToQueryTx struct{ tx *gorm.Association }

func (a salvosBelongsToQueryTx) Find() (result *models.SearchQuery, err error) {
	return result, a.tx.Find(&result)
}

func (a salvosBelongsToQueryTx) Append(values ...*models.SearchQuery) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a salvosBelongsToQueryTx) Replace(values ...*models.SearchQuery) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a salvosBelongsToQueryTx) Delete(values ...*models.SearchQuery) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a salvosBelongsToQueryTx) Clear() error {
	return a.tx.Clear()
}

func (a salvosBelongsToQueryTx) Count() int64 {
	return a.tx.Count()
}

func (a salvosBelongsToQueryTx) Unscoped() *salvosBelongsToQueryTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type salvosDo struct{ gen.DO }

type ISalvosDo interface {
	gen.SubQuery
	Debug() ISalvosDo
	WithContext(ctx context.Context) ISalvosDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISalvosDo
	WriteDB() ISalvosDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISalvosDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISalvosDo
	Not(conds ...gen.Condition) ISalvosDo
	Or(conds ...gen.Condition) ISalvosDo
	Select(conds ...field.Expr) ISalvosDo
	Where(conds ...gen.Condition) ISalvosDo
	Order(conds ...field.Expr) ISalvosDo
	Distinct(cols ...field.Expr) ISalvosDo
	Omit(cols ...field.Expr) ISalvosDo
	Join(table schema.Tabler, on ...field.Expr) ISalvosDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISalvosDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISalvosDo
	Group(cols ...field.Expr) ISalvosDo
	Having(conds ...gen.Condition) ISalvosDo
	Limit(limit int) ISalvosDo
	Offset(offset int) ISalvosDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISalvosDo
	Unscoped() ISalvosDo
	Create(values ...*models.Salvos) error
	CreateInBatches(values []*models.Salvos, batchSize int) error
	Save(values ...*models.Salvos) error
	First() (*models.Salvos, error)
	Take() (*models.Salvos, error)
	Last() (*models.Salvos, error)
	Find() ([]*models.Salvos, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Salvos, err error)
	FindInBatches(result *[]*models.Salvos, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Salvos) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISalvosDo
	Assign(attrs ...field.AssignExpr) ISalvosDo
	Joins(fields ...field.RelationField) ISalvosDo
	Preload(fields ...field.RelationField) ISalvosDo
	FirstOrInit() (*models.Salvos, error)
	FirstOrCreate() (*models.Salvos, error)
	FindByPage(offset int, limit int) (result []*models.Salvos, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISalvosDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s salvosDo) Debug() ISalvosDo {
	return s.withDO(s.DO.Debug())
}

func (s salvosDo) WithContext(ctx context.Context) ISalvosDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s salvosDo) ReadDB() ISalvosDo {
	return s.Clauses(dbresolver.Read)
}

func (s salvosDo) WriteDB() ISalvosDo {
	return s.Clauses(dbresolver.Write)
}

func (s salvosDo) Session(config *gorm.Session) ISalvosDo {
	return s.withDO(s.DO.Session(config))
}

func (s salvosDo) Clauses(conds ...clause.Expression) ISalvosDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s salvosDo) Returning(value interface{}, columns ...string) ISalvosDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s salvosDo) Not(conds ...gen.Condition) ISalvosDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s salvosDo) Or(conds ...gen.Condition) ISalvosDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s salvosDo) Select(conds ...field.Expr) ISalvosDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s salvosDo) Where(conds ...gen.Condition) ISalvosDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s salvosDo) Order(conds ...field.Expr) ISalvosDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s salvosDo) Distinct(cols ...field.Expr) ISalvosDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s salvosDo) Omit(cols ...field.Expr) ISalvosDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s salvosDo) Join(table schema.Tabler, on ...field.Expr) ISalvosDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s salvosDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISalvosDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s salvosDo) RightJoin(table schema.Tabler, on ...field.Expr) ISalvosDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s salvosDo) Group(cols ...field.Expr) ISalvosDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s salvosDo) Having(conds ...gen.Condition) ISalvosDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s salvosDo) Limit(limit int) ISalvosDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s salvosDo) Offset(offset int) ISalvosDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s salvosDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISalvosDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s salvosDo) Unscoped() ISalvosDo {
	return s.withDO(s.DO.Unscoped())
}

func (s salvosDo) Create(values ...*models.Salvos) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s salvosDo) CreateInBatches(values []*models.Salvos, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s salvosDo) Save(values ...*models.Salvos) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s salvosDo) First() (*models.Salvos, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Salvos), nil
	}
}

func (s salvosDo) Take() (*models.Salvos, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Salvos), nil
	}
}

func (s salvosDo) Last() (*models.Salvos, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Salvos), nil
	}
}

func (s salvosDo) Find() ([]*models.Salvos, error) {
	result, err := s.DO.Find()
	return result.([]*models.Salvos), err
}

func (s salvosDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Salvos, err error) {
	buf := make([]*models.Salvos, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s salvosDo) FindInBatches(result *[]*models.Salvos, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s salvosDo) Attrs(attrs ...field.AssignExpr) ISalvosDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s salvosDo) Assign(attrs ...field.AssignExpr) ISalvosDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s salvosDo) Joins(fields ...field.RelationField) ISalvosDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s salvosDo) Preload(fields ...field.RelationField) ISalvosDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s salvosDo) FirstOrInit() (*models.Salvos, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Salvos), nil
	}
}

func (s salvosDo) FirstOrCreate() (*models.Salvos, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Salvos), nil
	}
}

func (s salvosDo) FindByPage(offset int, limit int) (result []*models.Salvos, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s salvosDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s salvosDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s salvosDo) Delete(models ...*models.Salvos) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *salvosDo) withDO(do gen.Dao) *salvosDo {
	s.DO = *do.(*gen.DO)
	return s
}
