// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"dealscanner/internal/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newScannerRuntimeState(db *gorm.DB, opts ...gen.DOOption) scannerRuntimeState {
	_scannerRuntimeState := scannerRuntimeState{}

	_scannerRuntimeState.scannerRuntimeStateDo.UseDB(db, opts...)
	_scannerRuntimeState.scannerRuntimeStateDo.UseModel(&models.ScannerRuntimeState{})

	tableName := _scannerRuntimeState.scannerRuntimeStateDo.TableName()
	_scannerRuntimeState.ALL = field.NewAsterisk(tableName)
	_scannerRuntimeState.ID = field.NewString(tableName, "id")
	_scannerRuntimeState.SteamScanCount = field.NewInt(tableName, "steamScanCount")
	_scannerRuntimeState.CsTradeScanCount = field.NewInt(tableName, "csTradeScanCount")
	_scannerRuntimeState.ScheduledRuns = field.NewInt(tableName, "scheduledRuns")
	_scannerRuntimeState.TotalScheduledRuntimeMs = field.NewInt64(tableName, "totalScheduledRuntimeMs")
	_scannerRuntimeState.LastStartedAt = field.NewTime(tableName, "lastStartedAt")
	_scannerRuntimeState.LastStoppedAt = field.NewTime(tableName, "lastStoppedAt")
	_scannerRuntimeState.UpdatedAt = field.NewTime(tableName, "updatedAt")

	_scannerRuntimeState.fillFieldMap()

	return _scannerRuntimeState
}

type scannerRuntimeState struct {
	scannerRuntimeStateDo scannerRuntimeStateDo

	ALL                     field.Asterisk
	ID                      field.String
	SteamScanCount          field.Int
	CsTradeScanCount        field.Int
	ScheduledRuns           field.Int
	TotalScheduledRuntimeMs field.Int64
	LastStartedAt           field.Time
	LastStoppedAt           field.Time
	UpdatedAt               field.Time

	fieldMap map[string]field.Expr
}

func (s scannerRuntimeState) Table(newTableName string) *scannerRuntimeState {
	s.scannerRuntimeStateDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s scannerRuntimeState) As(alias string) *scannerRuntimeState {
	s.scannerRuntimeStateDo.DO = *(s.scannerRuntimeStateDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *scannerRuntimeState) updateTableName(table string) *scannerRuntimeState {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewString(table, "id")
	s.SteamScanCount = field.NewInt(table, "steamScanCount")
	s.CsTradeScanCount = field.NewInt(table, "csTradeScanCount")
	s.ScheduledRuns = field.NewInt(table, "scheduledRuns")
	s.TotalScheduledRuntimeMs = field.NewInt64(table, "totalScheduledRuntimeMs")
	s.LastStartedAt = field.NewTime(table, "lastStartedAt")
	s.LastStoppedAt = field.NewTime(table, "lastStoppedAt")
	s.UpdatedAt = field.NewTime(table, "updatedAt")

	s.fillFieldMap()

	return s
}

func (s *scannerRuntimeState) WithContext(ctx context.Context) IScannerRuntimeStateDo {
	return s.scannerRuntimeStateDo.WithContext(ctx)
}

func (s scannerRuntimeState) TableName() string { return s.scannerRuntimeStateDo.TableName() }

func (s scannerRuntimeState) Alias() string { return s.scannerRuntimeStateDo.Alias() }

func (s scannerRuntimeState) Columns(cols ...field.Expr) gen.Columns {
	return s.scannerRuntimeStateDo.Columns(cols...)
}

func (s *scannerRuntimeState) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *scannerRuntimeState) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 8)
	s.fieldMap["id"] = s.ID
	s.fieldMap["steamScanCount"] = s.SteamScanCount
	s.fieldMap["csTradeScanCount"] = s.CsTradeScanCount
	s.fieldMap["scheduledRuns"] = s.ScheduledRuns
	s.fieldMap["totalScheduledRuntimeMs"] = s.TotalScheduledRuntimeMs
	s.fieldMap["lastStartedAt"] = s.LastStartedAt
	s.fieldMap["lastStoppedAt"] = s.LastStoppedAt
	s.fieldMap["updatedAt"] = s.UpdatedAt
}

func (s scannerRuntimeState) clone(db *gorm.DB) scannerRuntimeState {
	s.scannerRuntimeStateDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s scannerRuntimeState) replaceDB(db *gorm.DB) scannerRuntimeState {
	s.scannerRuntimeStateDo.ReplaceDB(db)
	return s
}

type scannerRuntimeStateDo struct{ gen.DO }

type IScannerRuntimeStateDo interface {
	gen.SubQuery
	Debug() IScannerRuntimeStateDo
	WithContext(ctx context.Context) IScannerRuntimeStateDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IScannerRuntimeStateDo
	WriteDB() IScannerRuntimeStateDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IScannerRuntimeStateDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IScannerRuntimeStateDo
	Not(conds ...gen.Condition) IScannerRuntimeStateDo
	Or(conds ...gen.Condition) IScannerRuntimeStateDo
	Select(conds ...field.Expr) IScannerRuntimeStateDo
	Where(conds ...gen.Condition) IScannerRuntimeStateDo
	Order(conds ...field.Expr) IScannerRuntimeStateDo
	Distinct(cols ...field.Expr) IScannerRuntimeStateDo
	Omit(cols ...field.Expr) IScannerRuntimeStateDo
	Join(table schema.Tabler, on ...field.Expr) IScannerRuntimeStateDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IScannerRuntimeStateDo
	RightJoin(table schema.Tabler, on ...field.Expr) IScannerRuntimeStateDo
	Group(cols ...field.Expr) IScannerRuntimeStateDo
	Having(conds ...gen.Condition) IScannerRuntimeStateDo
	Limit(limit int) IScannerRuntimeStateDo
	Offset(offset int) IScannerRuntimeStateDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IScannerRuntimeStateDo
	Unscoped() IScannerRuntimeStateDo
	Create(values ...*models.ScannerRuntimeState) error
	CreateInBatches(values []*models.ScannerRuntimeState, batchSize int) error
	Save(values ...*models.ScannerRuntimeState) error
	First() (*models.ScannerRuntimeState, error)
	Take() (*models.ScannerRuntimeState, error)
	Last() (*models.ScannerRuntimeState, error)
	Find() ([]*models.ScannerRuntimeState, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ScannerRuntimeState, err error)
	FindInBatches(result *[]*models.ScannerRuntimeState, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.ScannerRuntimeState) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IScannerRuntimeStateDo
	Assign(attrs ...field.AssignExpr) IScannerRuntimeStateDo
	Joins(fields ...field.RelationField) IScannerRuntimeStateDo
	Preload(fields ...field.RelationField) IScannerRuntimeStateDo
	FirstOrInit() (*models.ScannerRuntimeState, error)
	FirstOrCreate() (*models.ScannerRuntimeState, error)
	FindByPage(offset int, limit int) (result []*models.ScannerRuntimeState, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IScannerRuntimeStateDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s scannerRuntimeStateDo) Debug() IScannerRuntimeStateDo {
	return s.withDO(s.DO.Debug())
}

func (s scannerRuntimeStateDo) WithContext(ctx context.Context) IScannerRuntimeStateDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s scannerRuntimeStateDo) ReadDB() IScannerRuntimeStateDo {
	return s.Clauses(dbresolver.Read)
}

func (s scannerRuntimeStateDo) WriteDB() IScannerRuntimeStateDo {
	return s.Clauses(dbresolver.Write)
}

func (s scannerRuntimeStateDo) Session(config *gorm.Session) IScannerRuntimeStateDo {
	return s.withDO(s.DO.Session(config))
}

func (s scannerRuntimeStateDo) Clauses(conds ...clause.Expression) IScannerRuntimeStateDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s scannerRuntimeStateDo) Returning(value interface{}, columns ...string) IScannerRuntimeStateDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s scannerRuntimeStateDo) Not(conds ...gen.Condition) IScannerRuntimeStateDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s scannerRuntimeStateDo) Or(conds ...gen.Condition) IScannerRuntimeStateDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s scannerRuntimeStateDo) Select(conds ...field.Expr) IScannerRuntimeStateDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s scannerRuntimeStateDo) Where(conds ...gen.Condition) IScannerRuntimeStateDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s scannerRuntimeStateDo) Order(conds ...field.Expr) IScannerRuntimeStateDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s scannerRuntimeStateDo) Distinct(cols ...field.Expr) IScannerRuntimeStateDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s scannerRuntimeStateDo) Omit(cols ...field.Expr) IScannerRuntimeStateDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s scannerRuntimeStateDo) Join(table schema.Tabler, on ...field.Expr) IScannerRuntimeStateDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s scannerRuntimeStateDo) LeftJoin(table schema.Tabler, on ...field.Expr) IScannerRuntimeStateDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s scannerRuntimeStateDo) RightJoin(table schema.Tabler, on ...field.Expr) IScannerRuntimeStateDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s scannerRuntimeStateDo) Group(cols ...field.Expr) IScannerRuntimeStateDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s scannerRuntimeStateDo) Having(conds ...gen.Condition) IScannerRuntimeStateDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s scannerRuntimeStateDo) Limit(limit int) IScannerRuntimeStateDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s scannerRuntimeStateDo) Offset(offset int) IScannerRuntimeStateDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s scannerRuntimeStateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IScannerRuntimeStateDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s scannerRuntimeStateDo) Unscoped() IScannerRuntimeStateDo {
	return s.withDO(s.DO.Unscoped())
}

func (s scannerRuntimeStateDo) Create(values ...*models.ScannerRuntimeState) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s scannerRuntimeStateDo) CreateInBatches(values []*models.ScannerRuntimeState, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s scannerRuntimeStateDo) Save(values ...*models.ScannerRuntimeState) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s scannerRuntimeStateDo) First() (*models.ScannerRuntimeState, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.ScannerRuntimeState), nil
	}
}

func (s scannerRuntimeStateDo) Take() (*models.ScannerRuntimeState, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.ScannerRuntimeState), nil
	}
}

func (s scannerRuntimeStateDo) Last() (*models.ScannerRuntimeState, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.ScannerRuntimeState), nil
	}
}

func (s scannerRuntimeStateDo) Find() ([]*models.ScannerRuntimeState, error) {
	result, err := s.DO.Find()
	return result.([]*models.ScannerRuntimeState), err
}

func (s scannerRuntimeStateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ScannerRuntimeState, err error) {
	buf := make([]*models.ScannerRuntimeState, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s scannerRuntimeStateDo) FindInBatches(result *[]*models.ScannerRuntimeState, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s scannerRuntimeStateDo) Attrs(attrs ...field.AssignExpr) IScannerRuntimeStateDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s scannerRuntimeStateDo) Assign(attrs ...field.AssignExpr) IScannerRuntimeStateDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s scannerRuntimeStateDo) Joins(fields ...field.RelationField) IScannerRuntimeStateDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s scannerRuntimeStateDo) Preload(fields ...field.RelationField) IScannerRuntimeStateDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s scannerRuntimeStateDo) FirstOrInit() (*models.ScannerRuntimeState, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.ScannerRuntimeState), nil
	}
}

func (s scannerRuntimeStateDo) FirstOrCreate() (*models.ScannerRuntimeState, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.ScannerRuntimeState), nil
	}
}

func (s scannerRuntimeStateDo) FindByPage(offset int, limit int) (result []*models.ScannerRuntimeState, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s scannerRuntimeStateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s scannerRuntimeStateDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s scannerRuntimeStateDo) Delete(models ...*models.ScannerRuntimeState) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *scannerRuntimeStateDo) withDO(do gen.Dao) *scannerRuntimeStateDo {
	s.DO = *do.(*gen.DO)
	return s
}
