// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"dealscanner/internal/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newSteamMarket(db *gorm.DB, opts ...gen.DOOption) steamMarket {
	_steamMarket := steamMarket{}

	_steamMarket.steamMarketDo.UseDB(db, opts...)
	_steamMarket.steamMarketDo.UseModel(&models.SteamMarket{})

	tableName := _steamMarket.steamMarketDo.TableName()
	_steamMarket.ALL = field.NewAsterisk(tableName)
	_steamMarket.Name = field.NewString(tableName, "name")
	_steamMarket.DisplayUrl = field.NewString(tableName, "displayUrl")
	_steamMarket.MaxPrice = field.NewFloat64(tableName, "maxPrice")
	_steamMarket.LastPrice = field.NewFloat64(tableName, "lastPrice")
	_steamMarket.QueryId = field.NewString(tableName, "queryId")
	_steamMarket.Query = steamMarketBelongsToQuery{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Query", "models.SearchQuery"),
	}

	_steamMarket.fillFieldMap()

	return _steamMarket
}

type steamMarket struct {
	steamMarketDo steamMarketDo

	ALL        field.Asterisk
	Name       field.String
	DisplayUrl field.String
	MaxPrice   field.Float64
	LastPrice  field.Float64
	QueryId    field.String
	Query      steamMarketBelongsToQuery

	fieldMap map[string]field.Expr
}

func (s steamMarket) Table(newTableName string) *steamMarket {
	s.steamMarketDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s steamMarket) As(alias string) *steamMarket {
	s.steamMarketDo.DO = *(s.steamMarketDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *steamMarket) updateTableName(table string) *steamMarket {
	s.ALL = field.NewAsterisk(table)
	s.Name = field.NewString(table, "name")
	s.DisplayUrl = field.NewString(table, "displayUrl")
	s.MaxPrice = field.NewFloat64(table, "maxPrice")
	s.LastPrice = field.NewFloat64(table, "lastPrice")
	s.QueryId = field.NewString(table, "queryId")

	s.fillFieldMap()

	return s
}

func (s *steamMarket) WithContext(ctx context.Context) ISteamMarketDo {
	return s.steamMarketDo.WithContext(ctx)
}

func (s steamMarket) TableName() string { return s.steamMarketDo.TableName() }

func (s steamMarket) Alias() string { return s.steamMarketDo.Alias() }

func (s steamMarket) Columns(cols ...field.Expr) gen.Columns { return s.steamMarketDo.Columns(cols...) }

func (s *steamMarket) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *steamMarket) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 6)
	s.fieldMap["name"] = s.Name
	s.fieldMap["displayUrl"] = s.DisplayUrl
	s.fieldMap["maxPrice"] = s.MaxPrice
	s.fieldMap["lastPrice"] = s.LastPrice
	s.fieldMap["queryId"] = s.QueryId

}

func (s steamMarket) clone(db *gorm.DB) steamMarket {
	s.steamMarketDo.ReplaceConnPool(db.Statement.ConnPool)
	s.Query.db = db.Session(&gorm.Session{Initialized: true})
	s.Query.db.Statement.ConnPool = db.Statement.ConnPool
	return s
}

func (s steamMarket) replaceDB(db *gorm.DB) steamMarket {
	s.steamMarketDo.ReplaceDB(db)
	s.Query.db = db.Session(&gorm.Session{})
	return s
}

type steamMarketBelongsToQuery struct {
	db *gorm.DB

	field.RelationField
}

func (a steamMarketBelongsToQuery) Where(conds ...field.Expr) *steamMarketBelongsToQuery {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a steamMarketBelongsToQuery) WithContext(ctx context.Context) *steamMarketBelongsToQuery {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a steamMarketBelongsToQuery) Session(session *gorm.Session) *steamMarketBelongsToQuery {
	a.db = a.db.Session(session)
	return &a
}

func (a steamMarketBelongsToQuery) Model(m *models.SteamMarket) *steamMarketBelongsToQueryTx {
	return &steamMarketBelongsToQueryTx{a.db.Model(m).Association(a.Name())}
}

func (a steamMarketBelongsToQuery) Unscoped() *steamMarketBelongsToQuery {
	a.db = a.db.Unscoped()
	return &a
}

type steamMarketBelongsToQueryTx struct{ tx *gorm.Association }

func (a steamMarketBelongsToQueryTx) Find() (result *models.SearchQuery, err error) {
	return result, a.tx.Find(&result)
}

func (a steamMarketBelongsToQueryTx) Append(values ...*models.SearchQuery) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a steamMarketBelongsToQueryTx) Replace(values ...*models.SearchQuery) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a steamMarketBelongsToQueryTx) Delete(values ...*models.SearchQuery) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a steamMarketBelongsToQueryTx) Clear() error {
	return a.tx.Clear()
}

func (a steamMarketBelongsToQueryTx) Count() int64 {
	return a.tx.Count()
}

func (a steamMarketBelongsToQueryTx) Unscoped() *steamMarketBelongsToQueryTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type steamMarketDo struct{ gen.DO }

type ISteamMarketDo interface {
	gen.SubQuery
	Debug() ISteamMarketDo
	WithContext(ctx context.Context) ISteamMarketDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISteamMarketDo
	WriteDB() ISteamMarketDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISteamMarketDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISteamMarketDo
	Not(conds ...gen.Condition) ISteamMarketDo
	Or(conds ...gen.Condition) ISteamMarketDo
	Select(conds ...field.Expr) ISteamMarketDo
	Where(conds ...gen.Condition) ISteamMarketDo
	Order(conds ...field.Expr) ISteamMarketDo
	Distinct(cols ...field.Expr) ISteamMarketDo
	Omit(cols ...field.Expr) ISteamMarketDo
	Join(table schema.Tabler, on ...field.Expr) ISteamMarketDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISteamMarketDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISteamMarketDo
	Group(cols ...field.Expr) ISteamMarketDo
	Having(conds ...gen.Condition) ISteamMarketDo
	Limit(limit int) ISteamMarketDo
	Offset(offset int) ISteamMarketDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISteamMarketDo
	Unscoped() ISteamMarketDo
	Create(values ...*models.SteamMarket) error
	CreateInBatches(values []*models.SteamMarket, batchSize int) error
	Save(values ...*models.SteamMarket) error
	First() (*models.SteamMarket, error)
	Take() (*models.SteamMarket, error)
	Last() (*models.SteamMarket, error)
	Find() ([]*models.SteamMarket, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SteamMarket, err error)
	FindInBatches(result *[]*models.SteamMarket, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.SteamMarket) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISteamMarketDo
	Assign(attrs ...field.AssignExpr) ISteamMarketDo
	Joins(fields ...field.RelationField) ISteamMarketDo
	Preload(fields ...field.RelationField) ISteamMarketDo
	FirstOrInit() (*models.SteamMarket, error)
	FirstOrCreate() (*models.SteamMarket, error)
	FindByPage(offset int, limit int) (result []*models.SteamMarket, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISteamMarketDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s steamMarketDo) Debug() ISteamMarketDo {
	return s.withDO(s.DO.Debug())
}

func (s steamMarketDo) WithContext(ctx context.Context) ISteamMarketDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s steamMarketDo) ReadDB() ISteamMarketDo {
	return s.Clauses(dbresolver.Read)
}

func (s steamMarketDo) WriteDB() ISteamMarketDo {
	return s.Clauses(dbresolver.Write)
}

func (s steamMarketDo) Session(config *gorm.Session) ISteamMarketDo {
	return s.withDO(s.DO.Session(config))
}

func (s steamMarketDo) Clauses(conds ...clause.Expression) ISteamMarketDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s steamMarketDo) Returning(value interface{}, columns ...string) ISteamMarketDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s steamMarketDo) Not(conds ...gen.Condition) ISteamMarketDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s steamMarketDo) Or(conds ...gen.Condition) ISteamMarketDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s steamMarketDo) Select(conds ...field.Expr) ISteamMarketDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s steamMarketDo) Where(conds ...gen.Condition) ISteamMarketDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s steamMarketDo) Order(conds ...field.Expr) ISteamMarketDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s steamMarketDo) Distinct(cols ...field.Expr) ISteamMarketDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s steamMarketDo) Omit(cols ...field.Expr) ISteamMarketDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s steamMarketDo) Join(table schema.Tabler, on ...field.Expr) ISteamMarketDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s steamMarketDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISteamMarketDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s steamMarketDo) RightJoin(table schema.Tabler, on ...field.Expr) ISteamMarketDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s steamMarketDo) Group(cols ...field.Expr) ISteamMarketDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s steamMarketDo) Having(conds ...gen.Condition) ISteamMarketDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s steamMarketDo) Limit(limit int) ISteamMarketDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s steamMarketDo) Offset(offset int) ISteamMarketDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s steamMarketDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISteamMarketDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s steamMarketDo) Unscoped() ISteamMarketDo {
	return s.withDO(s.DO.Unscoped())
}

func (s steamMarketDo) Create(values ...*models.SteamMarket) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s steamMarketDo) CreateInBatches(values []*models.SteamMarket, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s steamMarketDo) Save(values ...*models.SteamMarket) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s steamMarketDo) First() (*models.SteamMarket, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.SteamMarket), nil
	}
}

func (s steamMarketDo) Take() (*models.SteamMarket, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.SteamMarket), nil
	}
}

func (s steamMarketDo) Last() (*models.SteamMarket, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.SteamMarket), nil
	}
}

func (s steamMarketDo) Find() ([]*models.SteamMarket, error) {
	result, err := s.DO.Find()
	return result.([]*models.SteamMarket), err
}

func (s steamMarketDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SteamMarket, err error) {
	buf := make([]*models.SteamMarket, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s steamMarketDo) FindInBatches(result *[]*models.SteamMarket, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s steamMarketDo) Attrs(attrs ...field.AssignExpr) ISteamMarketDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s steamMarketDo) Assign(attrs ...field.AssignExpr) ISteamMarketDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s steamMarketDo) Joins(fields ...field.RelationField) ISteamMarketDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s steamMarketDo) Preload(fields ...field.RelationField) ISteamMarketDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s steamMarketDo) FirstOrInit() (*models.SteamMarket, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.SteamMarket), nil
	}
}

func (s steamMarketDo) FirstOrCreate() (*models.SteamMarket, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.SteamMarket), nil
	}
}

func (s steamMarketDo) FindByPage(offset int, limit int) (result []*models.SteamMarket, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s steamMarketDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s steamMarketDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s steamMarketDo) Delete(models ...*models.SteamMarket) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *steamMarketDo) withDO(do gen.Dao) *steamMarketDo {
	s.DO = *do.(*gen.DO)
	return s
}
