// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"dealscanner/internal/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newTtlItem(db *gorm.DB, opts ...gen.DOOption) ttlItem {
	_ttlItem := ttlItem{}

	_ttlItem.ttlItemDo.UseDB(db, opts...)
	_ttlItem.ttlItemDo.UseModel(&models.TtlItem{})

	tableName := _ttlItem.ttlItemDo.TableName()
	_ttlItem.ALL = field.NewAsterisk(tableName)
	_ttlItem.ItemId = field.NewString(tableName, "itemId")
	_ttlItem.Scanner = field.NewInt(tableName, "scanner")
	_ttlItem.LastUpdated = field.NewTime(tableName, "lastUpdated")

	_ttlItem.fillFieldMap()

	return _ttlItem
}

type ttlItem struct {
	ttlItemDo ttlItemDo

	ALL         field.Asterisk
	ItemId      field.String
	Scanner     field.Int
	LastUpdated field.Time

	fieldMap map[string]field.Expr
}

func (t ttlItem) Table(newTableName string) *ttlItem {
	t.ttlItemDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t ttlItem) As(alias string) *ttlItem {
	t.ttlItemDo.DO = *(t.ttlItemDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *ttlItem) updateTableName(table string) *ttlItem {
	t.ALL = field.NewAsterisk(table)
	t.ItemId = field.NewString(table, "itemId")
	t.Scanner = field.NewInt(table, "scanner")
	t.LastUpdated = field.NewTime(table, "lastUpdated")

	t.fillFieldMap()

	return t
}

func (t *ttlItem) WithContext(ctx context.Context) ITtlItemDo { return t.ttlItemDo.WithContext(ctx) }

func (t ttlItem) TableName() string { return t.ttlItemDo.TableName() }

func (t ttlItem) Alias() string { return t.ttlItemDo.Alias() }

func (t ttlItem) Columns(cols ...field.Expr) gen.Columns { return t.ttlItemDo.Columns(cols...) }

func (t *ttlItem) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *ttlItem) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 3)
	t.fieldMap["itemId"] = t.ItemId
	t.fieldMap["scanner"] = t.Scanner
	t.fieldMap["lastUpdated"] = t.LastUpdated
}

func (t ttlItem) clone(db *gorm.DB) ttlItem {
	t.ttlItemDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t ttlItem) replaceDB(db *gorm.DB) ttlItem {
	t.ttlItemDo.ReplaceDB(db)
	return t
}

type ttlItemDo struct{ gen.DO }

type ITtlItemDo interface {
	gen.SubQuery
	Debug() ITtlItemDo
	WithContext(ctx context.Context) ITtlItemDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITtlItemDo
	WriteDB() ITtlItemDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITtlItemDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITtlItemDo
	Not(conds ...gen.Condition) ITtlItemDo
	Or(conds ...gen.Condition) ITtlItemDo
	Select(conds ...field.Expr) ITtlItemDo
	Where(conds ...gen.Condition) ITtlItemDo
	Order(conds ...field.Expr) ITtlItemDo
	Distinct(cols ...field.Expr) ITtlItemDo
	Omit(cols ...field.Expr) ITtlItemDo
	Join(table schema.Tabler, on ...field.Expr) ITtlItemDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITtlItemDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITtlItemDo
	Group(cols ...field.Expr) ITtlItemDo
	Having(conds ...gen.Condition) ITtlItemDo
	Limit(limit int) ITtlItemDo
	Offset(offset int) ITtlItemDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITtlItemDo
	Unscoped() ITtlItemDo
	Create(values ...*models.TtlItem) error
	CreateInBatches(values []*models.TtlItem, batchSize int) error
	Save(values ...*models.TtlItem) error
	First() (*models.TtlItem, error)
	Take() (*models.TtlItem, error)
	Last() (*models.TtlItem, error)
	Find() ([]*models.TtlItem, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.TtlItem, err error)
	FindInBatches(result *[]*models.TtlItem, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.TtlItem) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITtlItemDo
	Assign(attrs ...field.AssignExpr) ITtlItemDo
	Joins(fields ...field.RelationField) ITtlItemDo
	Preload(fields ...field.RelationField) ITtlItemDo
	FirstOrInit() (*models.TtlItem, error)
	FirstOrCreate() (*models.TtlItem, error)
	FindByPage(offset int, limit int) (result []*models.TtlItem, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITtlItemDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t ttlItemDo) Debug() ITtlItemDo {
	return t.withDO(t.DO.Debug())
}

func (t ttlItemDo) WithContext(ctx context.Context) ITtlItemDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t ttlItemDo) ReadDB() ITtlItemDo {
	return t.Clauses(dbresolver.Read)
}

func (t ttlItemDo) WriteDB() ITtlItemDo {
	return t.Clauses(dbresolver.Write)
}

func (t ttlItemDo) Session(config *gorm.Session) ITtlItemDo {
	return t.withDO(t.DO.Session(config))
}

func (t ttlItemDo) Clauses(conds ...clause.Expression) ITtlItemDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t ttlItemDo) Returning(value interface{}, columns ...string) ITtlItemDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t ttlItemDo) Not(conds ...gen.Condition) ITtlItemDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t ttlItemDo) Or(conds ...gen.Condition) ITtlItemDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t ttlItemDo) Select(conds ...field.Expr) ITtlItemDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t ttlItemDo) Where(conds ...gen.Condition) ITtlItemDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t ttlItemDo) Order(conds ...field.Expr) ITtlItemDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t ttlItemDo) Distinct(cols ...field.Expr) ITtlItemDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t ttlItemDo) Omit(cols ...field.Expr) ITtlItemDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t ttlItemDo) Join(table schema.Tabler, on ...field.Expr) ITtlItemDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t ttlItemDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITtlItemDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t ttlItemDo) RightJoin(table schema.Tabler, on ...field.Expr) ITtlItemDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t ttlItemDo) Group(cols ...field.Expr) ITtlItemDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t ttlItemDo) Having(conds ...gen.Condition) ITtlItemDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t ttlItemDo) Limit(limit int) ITtlItemDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t ttlItemDo) Offset(offset int) ITtlItemDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t ttlItemDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITtlItemDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t ttlItemDo) Unscoped() ITtlItemDo {
	return t.withDO(t.DO.Unscoped())
}

func (t ttlItemDo) Create(values ...*models.TtlItem) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t ttlItemDo) CreateInBatches(values []*models.TtlItem, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t ttlItemDo) Save(values ...*models.TtlItem) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t ttlItemDo) First() (*models.TtlItem, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.TtlItem), nil
	}
}

func (t ttlItemDo) Take() (*models.TtlItem, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.TtlItem), nil
	}
}

func (t ttlItemDo) Last() (*models.TtlItem, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.TtlItem), nil
	}
}

func (t ttlItemDo) Find() ([]*models.TtlItem, error) {
	result, err := t.DO.Find()
	return result.([]*models.TtlItem), err
}

func (t ttlItemDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.TtlItem, err error) {
	buf := make([]*models.TtlItem, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t ttlItemDo) FindInBatches(result *[]*models.TtlItem, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t ttlItemDo) Attrs(attrs ...field.AssignExpr) ITtlItemDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t ttlItemDo) Assign(attrs ...field.AssignExpr) ITtlItemDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t ttlItemDo) Joins(fields ...field.RelationField) ITtlItemDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t ttlItemDo) Preload(fields ...field.RelationField) ITtlItemDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t ttlItemDo) FirstOrInit() (*models.TtlItem, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.TtlItem), nil
	}
}

func (t ttlItemDo) FirstOrCreate() (*models.TtlItem, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.TtlItem), nil
	}
}

func (t ttlItemDo) FindByPage(offset int, limit int) (result []*models.TtlItem, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t ttlItemDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t ttlItemDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t ttlItemDo) Delete(models ...*models.TtlItem) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *ttlItemDo) withDO(do gen.Dao) *ttlItemDo {
	t.DO = *do.(*gen.DO)
	return t
}
