// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"dealscanner/internal/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newUserQuery(db *gorm.DB, opts ...gen.DOOption) userQuery {
	_userQuery := userQuery{}

	_userQuery.userQueryDo.UseDB(db, opts...)
	_userQuery.userQueryDo.UseModel(&models.UserQuery{})

	tableName := _userQuery.userQueryDo.TableName()
	_userQuery.ALL = field.NewAsterisk(tableName)
	_userQuery.ID = field.NewString(tableName, "id")
	_userQuery.UserId = field.NewString(tableName, "userId")
	_userQuery.QueryId = field.NewString(tableName, "queryId")
	_userQuery.QueryType = field.NewString(tableName, "queryType")
	_userQuery.CreatedAt = field.NewTime(tableName, "createdAt")

	_userQuery.fillFieldMap()

	return _userQuery
}

type userQuery struct {
	userQueryDo userQueryDo

	ALL       field.Asterisk
	ID        field.String
	UserId    field.String
	QueryId   field.String
	QueryType field.String
	CreatedAt field.Time

	fieldMap map[string]field.Expr
}

func (u userQuery) Table(newTableName string) *userQuery {
	u.userQueryDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userQuery) As(alias string) *userQuery {
	u.userQueryDo.DO = *(u.userQueryDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userQuery) updateTableName(table string) *userQuery {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewString(table, "id")
	u.UserId = field.NewString(table, "userId")
	u.QueryId = field.NewString(table, "queryId")
	u.QueryType = field.NewString(table, "queryType")
	u.CreatedAt = field.NewTime(table, "createdAt")

	u.fillFieldMap()

	return u
}

func (u *userQuery) WithContext(ctx context.Context) IUserQueryDo {
	return u.userQueryDo.WithContext(ctx)
}

func (u userQuery) TableName() string { return u.userQueryDo.TableName() }

func (u userQuery) Alias() string { return u.userQueryDo.Alias() }

func (u userQuery) Columns(cols ...field.Expr) gen.Columns { return u.userQueryDo.Columns(cols...) }

func (u *userQuery) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userQuery) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 5)
	u.fieldMap["id"] = u.ID
	u.fieldMap["userId"] = u.UserId
	u.fieldMap["queryId"] = u.QueryId
	u.fieldMap["queryType"] = u.QueryType
	u.fieldMap["createdAt"] = u.CreatedAt
}

func (u userQuery) clone(db *gorm.DB) userQuery {
	u.userQueryDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userQuery) replaceDB(db *gorm.DB) userQuery {
	u.userQueryDo.ReplaceDB(db)
	return u
}

type userQueryDo struct{ gen.DO }

type IUserQueryDo interface {
	gen.SubQuery
	Debug() IUserQueryDo
	WithContext(ctx context.Context) IUserQueryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserQueryDo
	WriteDB() IUserQueryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserQueryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserQueryDo
	Not(conds ...gen.Condition) IUserQueryDo
	Or(conds ...gen.Condition) IUserQueryDo
	Select(conds ...field.Expr) IUserQueryDo
	Where(conds ...gen.Condition) IUserQueryDo
	Order(conds ...field.Expr) IUserQueryDo
	Distinct(cols ...field.Expr) IUserQueryDo
	Omit(cols ...field.Expr) IUserQueryDo
	Join(table schema.Tabler, on ...field.Expr) IUserQueryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserQueryDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserQueryDo
	Group(cols ...field.Expr) IUserQueryDo
	Having(conds ...gen.Condition) IUserQueryDo
	Limit(limit int) IUserQueryDo
	Offset(offset int) IUserQueryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserQueryDo
	Unscoped() IUserQueryDo
	Create(values ...*models.UserQuery) error
	CreateInBatches(values []*models.UserQuery, batchSize int) error
	Save(values ...*models.UserQuery) error
	First() (*models.UserQuery, error)
	Take() (*models.UserQuery, error)
	Last() (*models.UserQuery, error)
	Find() ([]*models.UserQuery, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.UserQuery, err error)
	FindInBatches(result *[]*models.UserQuery, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.UserQuery) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserQueryDo
	Assign(attrs ...field.AssignExpr) IUserQueryDo
	Joins(fields ...field.RelationField) IUserQueryDo
	Preload(fields ...field.RelationField) IUserQueryDo
	FirstOrInit() (*models.UserQuery, error)
	FirstOrCreate() (*models.UserQuery, error)
	FindByPage(offset int, limit int) (result []*models.UserQuery, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserQueryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u userQueryDo) Debug() IUserQueryDo {
	return u.withDO(u.DO.Debug())
}

func (u userQueryDo) WithContext(ctx context.Context) IUserQueryDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userQueryDo) ReadDB() IUserQueryDo {
	return u.Clauses(dbresolver.Read)
}

func (u userQueryDo) WriteDB() IUserQueryDo {
	return u.Clauses(dbresolver.Write)
}

func (u userQueryDo) Session(config *gorm.Session) IUserQueryDo {
	return u.withDO(u.DO.Session(config))
}

func (u userQueryDo) Clauses(conds ...clause.Expression) IUserQueryDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userQueryDo) Returning(value interface{}, columns ...string) IUserQueryDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userQueryDo) Not(conds ...gen.Condition) IUserQueryDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userQueryDo) Or(conds ...gen.Condition) IUserQueryDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userQueryDo) Select(conds ...field.Expr) IUserQueryDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userQueryDo) Where(conds ...gen.Condition) IUserQueryDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userQueryDo) Order(conds ...field.Expr) IUserQueryDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userQueryDo) Distinct(cols ...field.Expr) IUserQueryDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userQueryDo) Omit(cols ...field.Expr) IUserQueryDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userQueryDo) Join(table schema.Tabler, on ...field.Expr) IUserQueryDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userQueryDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserQueryDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userQueryDo) RightJoin(table schema.Tabler, on ...field.Expr) IUserQueryDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userQueryDo) Group(cols ...field.Expr) IUserQueryDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userQueryDo) Having(conds ...gen.Condition) IUserQueryDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userQueryDo) Limit(limit int) IUserQueryDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userQueryDo) Offset(offset int) IUserQueryDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userQueryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserQueryDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userQueryDo) Unscoped() IUserQueryDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userQueryDo) Create(values ...*models.UserQuery) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userQueryDo) CreateInBatches(values []*models.UserQuery, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userQueryDo) Save(values ...*models.UserQuery) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userQueryDo) First() (*models.UserQuery, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.UserQuery), nil
	}
}

func (u userQueryDo) Take() (*models.UserQuery, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.UserQuery), nil
	}
}

func (u userQueryDo) Last() (*models.UserQuery, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.UserQuery), nil
	}
}

func (u userQueryDo) Find() ([]*models.UserQuery, error) {
	result, err := u.DO.Find()
	return result.([]*models.UserQuery), err
}

func (u userQueryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.UserQuery, err error) {
	buf := make([]*models.UserQuery, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userQueryDo) FindInBatches(result *[]*models.UserQuery, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userQueryDo) Attrs(attrs ...field.AssignExpr) IUserQueryDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userQueryDo) Assign(attrs ...field.AssignExpr) IUserQueryDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userQueryDo) Joins(fields ...field.RelationField) IUserQueryDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userQueryDo) Preload(fields ...field.RelationField) IUserQueryDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userQueryDo) FirstOrInit() (*models.UserQuery, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.UserQuery), nil
	}
}

func (u userQueryDo) FirstOrCreate() (*models.UserQuery, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.UserQuery), nil
	}
}

func (u userQueryDo) FindByPage(offset int, limit int) (result []*models.UserQuery, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userQueryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userQueryDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userQueryDo) Delete(models ...*models.UserQuery) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userQueryDo) withDO(do gen.Dao) *userQueryDo {
	u.DO = *do.(*gen.DO)
	return u
}
